/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tgeneraltokenizer156015 tgeneraltokenizer156015;
typedef struct TNimObject TNimObject;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* TY156067[6];
typedef N_NIMCALL_PTR(void, TY2689) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2689 marker;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  tgeneraltokenizer156015  {
  TNimObject Sup;
NU8 Kind;
NI Start;
NI Length;
NCSTRING Buf;
NI Pos;
NU8 State;
};
typedef NimStringDesc* TY156079[68];
typedef NU8 tcharset88806[32];
typedef NimStringDesc* TY159067[48];
typedef NimStringDesc* TY159084[77];
typedef NimStringDesc* TY159051[37];
typedef NimStringDesc* TY159101[53];
typedef NimStringDesc* TY156073[33];
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, initgeneraltokenizer_156159)(tgeneraltokenizer156015* g, NCSTRING buf);
N_NIMCALL(void, nimnexttoken_156733)(tgeneraltokenizer156015* g);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NU8, nimgetkeyword_156225)(NimStringDesc* id);
N_NIMCALL(NI, nimnumberpostfix_156412)(tgeneraltokenizer156015* g, NI position);
N_NIMCALL(NI, nimnumber_156565)(tgeneraltokenizer156015* g, NI position);
N_NIMCALL(void, cppnexttoken_159062)(tgeneraltokenizer156015* g);
N_NIMCALL(void, clikenexttoken_158048)(tgeneraltokenizer156015* g, NimStringDesc** keywords, NI keywordsLen0, NU8 flags);
N_NIMCALL(NI, iskeyword_157983)(NimStringDesc** x, NI xLen0, NimStringDesc* y);
N_NIMCALL(NI, cmp_4148)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NI, generalnumber_157649)(tgeneraltokenizer156015* g, NI position);
N_NIMCALL(NI, generalstrlit_157812)(tgeneraltokenizer156015* g, NI position);
N_NIMCALL(void, csharpnexttoken_159079)(tgeneraltokenizer156015* g);
N_NIMCALL(void, cnexttoken_159046)(tgeneraltokenizer156015* g);
N_NIMCALL(void, javanexttoken_159096)(tgeneraltokenizer156015* g);
STRING_LITERAL(TMP461, "none", 4);
STRING_LITERAL(TMP462, "Nimrod", 6);
STRING_LITERAL(TMP463, "C++", 3);
STRING_LITERAL(TMP464, "C#", 2);
STRING_LITERAL(TMP465, "C", 1);
STRING_LITERAL(TMP466, "Java", 4);
NIM_CONST TY156067 sourcelanguagetostr_156066 = {((NimStringDesc*) &TMP461),
((NimStringDesc*) &TMP462),
((NimStringDesc*) &TMP463),
((NimStringDesc*) &TMP464),
((NimStringDesc*) &TMP465),
((NimStringDesc*) &TMP466)}
;
STRING_LITERAL(TMP478, "", 0);
STRING_LITERAL(TMP479, "addr", 4);
STRING_LITERAL(TMP480, "and", 3);
STRING_LITERAL(TMP481, "as", 2);
STRING_LITERAL(TMP482, "asm", 3);
STRING_LITERAL(TMP483, "atomic", 6);
STRING_LITERAL(TMP484, "bind", 4);
STRING_LITERAL(TMP485, "block", 5);
STRING_LITERAL(TMP486, "break", 5);
STRING_LITERAL(TMP487, "case", 4);
STRING_LITERAL(TMP488, "cast", 4);
STRING_LITERAL(TMP489, "const", 5);
STRING_LITERAL(TMP490, "continue", 8);
STRING_LITERAL(TMP491, "converter", 9);
STRING_LITERAL(TMP492, "discard", 7);
STRING_LITERAL(TMP493, "distinct", 8);
STRING_LITERAL(TMP494, "div", 3);
STRING_LITERAL(TMP495, "do", 2);
STRING_LITERAL(TMP496, "elif", 4);
STRING_LITERAL(TMP497, "else", 4);
STRING_LITERAL(TMP498, "end", 3);
STRING_LITERAL(TMP499, "enum", 4);
STRING_LITERAL(TMP500, "except", 6);
STRING_LITERAL(TMP501, "export", 6);
STRING_LITERAL(TMP502, "finally", 7);
STRING_LITERAL(TMP503, "for", 3);
STRING_LITERAL(TMP504, "from", 4);
STRING_LITERAL(TMP505, "generic", 7);
STRING_LITERAL(TMP506, "if", 2);
STRING_LITERAL(TMP507, "import", 6);
STRING_LITERAL(TMP508, "in", 2);
STRING_LITERAL(TMP509, "include", 7);
STRING_LITERAL(TMP510, "interface", 9);
STRING_LITERAL(TMP511, "is", 2);
STRING_LITERAL(TMP512, "isnot", 5);
STRING_LITERAL(TMP513, "iterator", 8);
STRING_LITERAL(TMP514, "lambda", 6);
STRING_LITERAL(TMP515, "let", 3);
STRING_LITERAL(TMP516, "macro", 5);
STRING_LITERAL(TMP517, "method", 6);
STRING_LITERAL(TMP518, "mixin", 5);
STRING_LITERAL(TMP519, "mod", 3);
STRING_LITERAL(TMP520, "nil", 3);
STRING_LITERAL(TMP521, "not", 3);
STRING_LITERAL(TMP522, "notin", 5);
STRING_LITERAL(TMP523, "object", 6);
STRING_LITERAL(TMP524, "of", 2);
STRING_LITERAL(TMP525, "or", 2);
STRING_LITERAL(TMP526, "out", 3);
STRING_LITERAL(TMP527, "proc", 4);
STRING_LITERAL(TMP528, "ptr", 3);
STRING_LITERAL(TMP529, "raise", 5);
STRING_LITERAL(TMP530, "ref", 3);
STRING_LITERAL(TMP531, "return", 6);
STRING_LITERAL(TMP532, "shl", 3);
STRING_LITERAL(TMP533, "shr", 3);
STRING_LITERAL(TMP534, "static", 6);
STRING_LITERAL(TMP535, "template", 8);
STRING_LITERAL(TMP536, "try", 3);
STRING_LITERAL(TMP537, "tuple", 5);
STRING_LITERAL(TMP538, "type", 4);
STRING_LITERAL(TMP539, "using", 5);
STRING_LITERAL(TMP540, "var", 3);
STRING_LITERAL(TMP541, "when", 4);
STRING_LITERAL(TMP542, "while", 5);
STRING_LITERAL(TMP543, "with", 4);
STRING_LITERAL(TMP544, "without", 7);
STRING_LITERAL(TMP545, "xor", 3);
STRING_LITERAL(TMP546, "yield", 5);
NIM_CONST TY156079 nimrodkeywords_156078 = {((NimStringDesc*) &TMP479),
((NimStringDesc*) &TMP480),
((NimStringDesc*) &TMP481),
((NimStringDesc*) &TMP482),
((NimStringDesc*) &TMP483),
((NimStringDesc*) &TMP484),
((NimStringDesc*) &TMP485),
((NimStringDesc*) &TMP486),
((NimStringDesc*) &TMP487),
((NimStringDesc*) &TMP488),
((NimStringDesc*) &TMP489),
((NimStringDesc*) &TMP490),
((NimStringDesc*) &TMP491),
((NimStringDesc*) &TMP492),
((NimStringDesc*) &TMP493),
((NimStringDesc*) &TMP494),
((NimStringDesc*) &TMP495),
((NimStringDesc*) &TMP496),
((NimStringDesc*) &TMP497),
((NimStringDesc*) &TMP498),
((NimStringDesc*) &TMP499),
((NimStringDesc*) &TMP500),
((NimStringDesc*) &TMP501),
((NimStringDesc*) &TMP502),
((NimStringDesc*) &TMP503),
((NimStringDesc*) &TMP504),
((NimStringDesc*) &TMP505),
((NimStringDesc*) &TMP506),
((NimStringDesc*) &TMP507),
((NimStringDesc*) &TMP508),
((NimStringDesc*) &TMP509),
((NimStringDesc*) &TMP510),
((NimStringDesc*) &TMP511),
((NimStringDesc*) &TMP512),
((NimStringDesc*) &TMP513),
((NimStringDesc*) &TMP514),
((NimStringDesc*) &TMP515),
((NimStringDesc*) &TMP516),
((NimStringDesc*) &TMP517),
((NimStringDesc*) &TMP518),
((NimStringDesc*) &TMP519),
((NimStringDesc*) &TMP520),
((NimStringDesc*) &TMP521),
((NimStringDesc*) &TMP522),
((NimStringDesc*) &TMP523),
((NimStringDesc*) &TMP524),
((NimStringDesc*) &TMP525),
((NimStringDesc*) &TMP526),
((NimStringDesc*) &TMP527),
((NimStringDesc*) &TMP528),
((NimStringDesc*) &TMP529),
((NimStringDesc*) &TMP530),
((NimStringDesc*) &TMP531),
((NimStringDesc*) &TMP532),
((NimStringDesc*) &TMP533),
((NimStringDesc*) &TMP534),
((NimStringDesc*) &TMP535),
((NimStringDesc*) &TMP536),
((NimStringDesc*) &TMP537),
((NimStringDesc*) &TMP538),
((NimStringDesc*) &TMP539),
((NimStringDesc*) &TMP540),
((NimStringDesc*) &TMP541),
((NimStringDesc*) &TMP542),
((NimStringDesc*) &TMP543),
((NimStringDesc*) &TMP544),
((NimStringDesc*) &TMP545),
((NimStringDesc*) &TMP546)}
;
static NIM_CONST tcharset88806 TMP547 = {
0x00, 0x00, 0x00, 0x00, 0x72, 0xEC, 0x00, 0xF4,
0x01, 0x00, 0x00, 0x50, 0x00, 0x00, 0x00, 0x50,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
STRING_LITERAL(TMP549, "auto", 4);
STRING_LITERAL(TMP550, "catch", 5);
STRING_LITERAL(TMP551, "char", 4);
STRING_LITERAL(TMP552, "class", 5);
STRING_LITERAL(TMP553, "default", 7);
STRING_LITERAL(TMP554, "delete", 6);
STRING_LITERAL(TMP555, "double", 6);
STRING_LITERAL(TMP556, "extern", 6);
STRING_LITERAL(TMP557, "float", 5);
STRING_LITERAL(TMP558, "friend", 6);
STRING_LITERAL(TMP559, "goto", 4);
STRING_LITERAL(TMP560, "inline", 6);
STRING_LITERAL(TMP561, "int", 3);
STRING_LITERAL(TMP562, "long", 4);
STRING_LITERAL(TMP563, "new", 3);
STRING_LITERAL(TMP564, "operator", 8);
STRING_LITERAL(TMP565, "private", 7);
STRING_LITERAL(TMP566, "protected", 9);
STRING_LITERAL(TMP567, "public", 6);
STRING_LITERAL(TMP568, "register", 8);
STRING_LITERAL(TMP569, "short", 5);
STRING_LITERAL(TMP570, "signed", 6);
STRING_LITERAL(TMP571, "sizeof", 6);
STRING_LITERAL(TMP572, "struct", 6);
STRING_LITERAL(TMP573, "switch", 6);
STRING_LITERAL(TMP574, "this", 4);
STRING_LITERAL(TMP575, "throw", 5);
STRING_LITERAL(TMP576, "typedef", 7);
STRING_LITERAL(TMP577, "union", 5);
STRING_LITERAL(TMP578, "unsigned", 8);
STRING_LITERAL(TMP579, "virtual", 7);
STRING_LITERAL(TMP580, "void", 4);
STRING_LITERAL(TMP581, "volatile", 8);
NIM_CONST TY159067 TMP548 = {((NimStringDesc*) &TMP482),
((NimStringDesc*) &TMP549),
((NimStringDesc*) &TMP486),
((NimStringDesc*) &TMP487),
((NimStringDesc*) &TMP550),
((NimStringDesc*) &TMP551),
((NimStringDesc*) &TMP552),
((NimStringDesc*) &TMP489),
((NimStringDesc*) &TMP490),
((NimStringDesc*) &TMP553),
((NimStringDesc*) &TMP554),
((NimStringDesc*) &TMP495),
((NimStringDesc*) &TMP555),
((NimStringDesc*) &TMP497),
((NimStringDesc*) &TMP499),
((NimStringDesc*) &TMP556),
((NimStringDesc*) &TMP557),
((NimStringDesc*) &TMP503),
((NimStringDesc*) &TMP558),
((NimStringDesc*) &TMP559),
((NimStringDesc*) &TMP506),
((NimStringDesc*) &TMP560),
((NimStringDesc*) &TMP561),
((NimStringDesc*) &TMP562),
((NimStringDesc*) &TMP563),
((NimStringDesc*) &TMP564),
((NimStringDesc*) &TMP565),
((NimStringDesc*) &TMP566),
((NimStringDesc*) &TMP567),
((NimStringDesc*) &TMP568),
((NimStringDesc*) &TMP531),
((NimStringDesc*) &TMP569),
((NimStringDesc*) &TMP570),
((NimStringDesc*) &TMP571),
((NimStringDesc*) &TMP534),
((NimStringDesc*) &TMP572),
((NimStringDesc*) &TMP573),
((NimStringDesc*) &TMP535),
((NimStringDesc*) &TMP574),
((NimStringDesc*) &TMP575),
((NimStringDesc*) &TMP536),
((NimStringDesc*) &TMP576),
((NimStringDesc*) &TMP577),
((NimStringDesc*) &TMP578),
((NimStringDesc*) &TMP579),
((NimStringDesc*) &TMP580),
((NimStringDesc*) &TMP581),
((NimStringDesc*) &TMP542)}
;
STRING_LITERAL(TMP583, "abstract", 8);
STRING_LITERAL(TMP584, "base", 4);
STRING_LITERAL(TMP585, "bool", 4);
STRING_LITERAL(TMP586, "byte", 4);
STRING_LITERAL(TMP587, "checked", 7);
STRING_LITERAL(TMP588, "decimal", 7);
STRING_LITERAL(TMP589, "delegate", 8);
STRING_LITERAL(TMP590, "event", 5);
STRING_LITERAL(TMP591, "explicit", 8);
STRING_LITERAL(TMP592, "false", 5);
STRING_LITERAL(TMP593, "fixed", 5);
STRING_LITERAL(TMP594, "foreach", 7);
STRING_LITERAL(TMP595, "implicit", 8);
STRING_LITERAL(TMP596, "internal", 8);
STRING_LITERAL(TMP597, "lock", 4);
STRING_LITERAL(TMP598, "namespace", 9);
STRING_LITERAL(TMP599, "null", 4);
STRING_LITERAL(TMP600, "override", 8);
STRING_LITERAL(TMP601, "params", 6);
STRING_LITERAL(TMP602, "readonly", 8);
STRING_LITERAL(TMP603, "sbyte", 5);
STRING_LITERAL(TMP604, "sealed", 6);
STRING_LITERAL(TMP605, "stackalloc", 10);
STRING_LITERAL(TMP606, "string", 6);
STRING_LITERAL(TMP607, "true", 4);
STRING_LITERAL(TMP608, "typeof", 6);
STRING_LITERAL(TMP609, "uint", 4);
STRING_LITERAL(TMP610, "ulong", 5);
STRING_LITERAL(TMP611, "unchecked", 9);
STRING_LITERAL(TMP612, "unsafe", 6);
STRING_LITERAL(TMP613, "ushort", 6);
NIM_CONST TY159084 TMP582 = {((NimStringDesc*) &TMP583),
((NimStringDesc*) &TMP481),
((NimStringDesc*) &TMP584),
((NimStringDesc*) &TMP585),
((NimStringDesc*) &TMP486),
((NimStringDesc*) &TMP586),
((NimStringDesc*) &TMP487),
((NimStringDesc*) &TMP550),
((NimStringDesc*) &TMP551),
((NimStringDesc*) &TMP587),
((NimStringDesc*) &TMP552),
((NimStringDesc*) &TMP489),
((NimStringDesc*) &TMP490),
((NimStringDesc*) &TMP588),
((NimStringDesc*) &TMP553),
((NimStringDesc*) &TMP589),
((NimStringDesc*) &TMP495),
((NimStringDesc*) &TMP555),
((NimStringDesc*) &TMP497),
((NimStringDesc*) &TMP499),
((NimStringDesc*) &TMP590),
((NimStringDesc*) &TMP591),
((NimStringDesc*) &TMP556),
((NimStringDesc*) &TMP592),
((NimStringDesc*) &TMP502),
((NimStringDesc*) &TMP593),
((NimStringDesc*) &TMP557),
((NimStringDesc*) &TMP503),
((NimStringDesc*) &TMP594),
((NimStringDesc*) &TMP559),
((NimStringDesc*) &TMP506),
((NimStringDesc*) &TMP595),
((NimStringDesc*) &TMP508),
((NimStringDesc*) &TMP561),
((NimStringDesc*) &TMP510),
((NimStringDesc*) &TMP596),
((NimStringDesc*) &TMP511),
((NimStringDesc*) &TMP597),
((NimStringDesc*) &TMP562),
((NimStringDesc*) &TMP598),
((NimStringDesc*) &TMP563),
((NimStringDesc*) &TMP599),
((NimStringDesc*) &TMP523),
((NimStringDesc*) &TMP564),
((NimStringDesc*) &TMP526),
((NimStringDesc*) &TMP600),
((NimStringDesc*) &TMP601),
((NimStringDesc*) &TMP565),
((NimStringDesc*) &TMP566),
((NimStringDesc*) &TMP567),
((NimStringDesc*) &TMP602),
((NimStringDesc*) &TMP530),
((NimStringDesc*) &TMP531),
((NimStringDesc*) &TMP603),
((NimStringDesc*) &TMP604),
((NimStringDesc*) &TMP569),
((NimStringDesc*) &TMP571),
((NimStringDesc*) &TMP605),
((NimStringDesc*) &TMP534),
((NimStringDesc*) &TMP606),
((NimStringDesc*) &TMP572),
((NimStringDesc*) &TMP573),
((NimStringDesc*) &TMP574),
((NimStringDesc*) &TMP575),
((NimStringDesc*) &TMP607),
((NimStringDesc*) &TMP536),
((NimStringDesc*) &TMP608),
((NimStringDesc*) &TMP609),
((NimStringDesc*) &TMP610),
((NimStringDesc*) &TMP611),
((NimStringDesc*) &TMP612),
((NimStringDesc*) &TMP613),
((NimStringDesc*) &TMP539),
((NimStringDesc*) &TMP579),
((NimStringDesc*) &TMP580),
((NimStringDesc*) &TMP581),
((NimStringDesc*) &TMP542)}
;
STRING_LITERAL(TMP615, "_Bool", 5);
STRING_LITERAL(TMP616, "_Complex", 8);
STRING_LITERAL(TMP617, "_Imaginary", 10);
STRING_LITERAL(TMP618, "restrict", 8);
NIM_CONST TY159051 TMP614 = {((NimStringDesc*) &TMP615),
((NimStringDesc*) &TMP616),
((NimStringDesc*) &TMP617),
((NimStringDesc*) &TMP549),
((NimStringDesc*) &TMP486),
((NimStringDesc*) &TMP487),
((NimStringDesc*) &TMP551),
((NimStringDesc*) &TMP489),
((NimStringDesc*) &TMP490),
((NimStringDesc*) &TMP553),
((NimStringDesc*) &TMP495),
((NimStringDesc*) &TMP555),
((NimStringDesc*) &TMP497),
((NimStringDesc*) &TMP499),
((NimStringDesc*) &TMP556),
((NimStringDesc*) &TMP557),
((NimStringDesc*) &TMP503),
((NimStringDesc*) &TMP559),
((NimStringDesc*) &TMP506),
((NimStringDesc*) &TMP560),
((NimStringDesc*) &TMP561),
((NimStringDesc*) &TMP562),
((NimStringDesc*) &TMP568),
((NimStringDesc*) &TMP618),
((NimStringDesc*) &TMP531),
((NimStringDesc*) &TMP569),
((NimStringDesc*) &TMP570),
((NimStringDesc*) &TMP571),
((NimStringDesc*) &TMP534),
((NimStringDesc*) &TMP572),
((NimStringDesc*) &TMP573),
((NimStringDesc*) &TMP576),
((NimStringDesc*) &TMP577),
((NimStringDesc*) &TMP578),
((NimStringDesc*) &TMP580),
((NimStringDesc*) &TMP581),
((NimStringDesc*) &TMP542)}
;
STRING_LITERAL(TMP620, "assert", 6);
STRING_LITERAL(TMP621, "boolean", 7);
STRING_LITERAL(TMP622, "extends", 7);
STRING_LITERAL(TMP623, "final", 5);
STRING_LITERAL(TMP624, "implements", 10);
STRING_LITERAL(TMP625, "instanceof", 10);
STRING_LITERAL(TMP626, "native", 6);
STRING_LITERAL(TMP627, "package", 7);
STRING_LITERAL(TMP628, "strictfp", 8);
STRING_LITERAL(TMP629, "super", 5);
STRING_LITERAL(TMP630, "synchronized", 12);
STRING_LITERAL(TMP631, "throws", 6);
STRING_LITERAL(TMP632, "transient", 9);
NIM_CONST TY159101 TMP619 = {((NimStringDesc*) &TMP583),
((NimStringDesc*) &TMP620),
((NimStringDesc*) &TMP621),
((NimStringDesc*) &TMP486),
((NimStringDesc*) &TMP586),
((NimStringDesc*) &TMP487),
((NimStringDesc*) &TMP550),
((NimStringDesc*) &TMP551),
((NimStringDesc*) &TMP552),
((NimStringDesc*) &TMP489),
((NimStringDesc*) &TMP490),
((NimStringDesc*) &TMP553),
((NimStringDesc*) &TMP495),
((NimStringDesc*) &TMP555),
((NimStringDesc*) &TMP497),
((NimStringDesc*) &TMP499),
((NimStringDesc*) &TMP622),
((NimStringDesc*) &TMP592),
((NimStringDesc*) &TMP623),
((NimStringDesc*) &TMP502),
((NimStringDesc*) &TMP557),
((NimStringDesc*) &TMP503),
((NimStringDesc*) &TMP559),
((NimStringDesc*) &TMP506),
((NimStringDesc*) &TMP624),
((NimStringDesc*) &TMP507),
((NimStringDesc*) &TMP625),
((NimStringDesc*) &TMP561),
((NimStringDesc*) &TMP510),
((NimStringDesc*) &TMP562),
((NimStringDesc*) &TMP626),
((NimStringDesc*) &TMP563),
((NimStringDesc*) &TMP599),
((NimStringDesc*) &TMP627),
((NimStringDesc*) &TMP565),
((NimStringDesc*) &TMP566),
((NimStringDesc*) &TMP567),
((NimStringDesc*) &TMP531),
((NimStringDesc*) &TMP569),
((NimStringDesc*) &TMP534),
((NimStringDesc*) &TMP628),
((NimStringDesc*) &TMP629),
((NimStringDesc*) &TMP573),
((NimStringDesc*) &TMP630),
((NimStringDesc*) &TMP574),
((NimStringDesc*) &TMP575),
((NimStringDesc*) &TMP631),
((NimStringDesc*) &TMP632),
((NimStringDesc*) &TMP607),
((NimStringDesc*) &TMP536),
((NimStringDesc*) &TMP580),
((NimStringDesc*) &TMP581),
((NimStringDesc*) &TMP542)}
;
STRING_LITERAL(TMP635, "Eof", 3);
STRING_LITERAL(TMP636, "None", 4);
STRING_LITERAL(TMP637, "Whitespace", 10);
STRING_LITERAL(TMP638, "DecNumber", 9);
STRING_LITERAL(TMP639, "BinNumber", 9);
STRING_LITERAL(TMP640, "HexNumber", 9);
STRING_LITERAL(TMP641, "OctNumber", 9);
STRING_LITERAL(TMP642, "FloatNumber", 11);
STRING_LITERAL(TMP643, "Identifier", 10);
STRING_LITERAL(TMP644, "Keyword", 7);
STRING_LITERAL(TMP645, "StringLit", 9);
STRING_LITERAL(TMP646, "LongStringLit", 13);
STRING_LITERAL(TMP647, "CharLit", 7);
STRING_LITERAL(TMP648, "EscapeSequence", 14);
STRING_LITERAL(TMP649, "Operator", 8);
STRING_LITERAL(TMP650, "Punctuation", 11);
STRING_LITERAL(TMP651, "Comment", 7);
STRING_LITERAL(TMP652, "LongComment", 11);
STRING_LITERAL(TMP653, "RegularExpression", 17);
STRING_LITERAL(TMP654, "TagStart", 8);
STRING_LITERAL(TMP655, "TagEnd", 6);
STRING_LITERAL(TMP656, "Key", 3);
STRING_LITERAL(TMP657, "Value", 5);
STRING_LITERAL(TMP658, "RawData", 7);
STRING_LITERAL(TMP659, "Assembler", 9);
STRING_LITERAL(TMP660, "Preprocessor", 12);
STRING_LITERAL(TMP661, "Directive", 9);
STRING_LITERAL(TMP662, "Command", 7);
STRING_LITERAL(TMP663, "Rule", 4);
STRING_LITERAL(TMP664, "Hyperlink", 9);
STRING_LITERAL(TMP665, "Label", 5);
STRING_LITERAL(TMP666, "Reference", 9);
STRING_LITERAL(TMP667, "Other", 5);
NIM_CONST TY156073 tokenclasstostr_156072 = {((NimStringDesc*) &TMP635),
((NimStringDesc*) &TMP636),
((NimStringDesc*) &TMP637),
((NimStringDesc*) &TMP638),
((NimStringDesc*) &TMP639),
((NimStringDesc*) &TMP640),
((NimStringDesc*) &TMP641),
((NimStringDesc*) &TMP642),
((NimStringDesc*) &TMP643),
((NimStringDesc*) &TMP644),
((NimStringDesc*) &TMP645),
((NimStringDesc*) &TMP646),
((NimStringDesc*) &TMP647),
((NimStringDesc*) &TMP648),
((NimStringDesc*) &TMP649),
((NimStringDesc*) &TMP650),
((NimStringDesc*) &TMP651),
((NimStringDesc*) &TMP652),
((NimStringDesc*) &TMP653),
((NimStringDesc*) &TMP654),
((NimStringDesc*) &TMP655),
((NimStringDesc*) &TMP656),
((NimStringDesc*) &TMP657),
((NimStringDesc*) &TMP658),
((NimStringDesc*) &TMP659),
((NimStringDesc*) &TMP660),
((NimStringDesc*) &TMP661),
((NimStringDesc*) &TMP662),
((NimStringDesc*) &TMP663),
((NimStringDesc*) &TMP664),
((NimStringDesc*) &TMP665),
((NimStringDesc*) &TMP666),
((NimStringDesc*) &TMP667)}
;
extern TNimType NTI2811; /* TObject */
TNimType NTI156015; /* TGeneralTokenizer */
TNimType NTI156013; /* TTokenClass */
extern TNimType NTI112; /* int */
extern TNimType NTI159; /* cstring */

N_NIMCALL(NU8, getsourcelanguage_156084)(NimStringDesc* name) {
	NU8 result;
	NU8 i_156145;
	NU8 res_156148;
	result = 0;
	i_156145 = 0;
	res_156148 = ((NU8) 1);
	while (1) {
		if (!(res_156148 <= ((NU8) 5))) goto LA1;
		i_156145 = res_156148;
		{
			NI LOC4;
			LOC4 = 0;
			LOC4 = nsuCmpIgnoreStyle(name, sourcelanguagetostr_156066[(i_156145)- 0]);
			if (!(LOC4 == 0)) goto LA5;
			result = i_156145;
			goto BeforeRet;
		}
		LA5: ;
		res_156148 += 1;
	} LA1: ;
	result = ((NU8) 0);
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, initgeneraltokenizer_156159)(tgeneraltokenizer156015* g, NCSTRING buf) {
	NI pos;
	(*g).Buf = buf;
	(*g).Kind = ((NU8) 0);
	(*g).Start = 0;
	(*g).Length = 0;
	(*g).State = ((NU8) 0);
	pos = 0;
	while (1) {
		if (!(((NU8)((*g).Buf[pos])) == ((NU8)(32)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(9)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(13)))) goto LA1;
		pos += 1;
	} LA1: ;
	(*g).Pos = pos;
}

N_NIMCALL(void, initgeneraltokenizer_156204)(tgeneraltokenizer156015* g, NimStringDesc* buf) {
	initgeneraltokenizer_156159(g, buf->data);
}

N_NIMCALL(NU8, nimgetkeyword_156225)(NimStringDesc* id) {
	NU8 result;
	NimStringDesc* k_156271;
	NI i_156402;
	result = 0;
	k_156271 = 0;
	i_156402 = 0;
	{
		if (!(((NI) (i_156402)) <= 67)) goto LA3;
		while (1) {
			k_156271 = nimrodkeywords_156078[(i_156402)- 0];
			{
				NI LOC8;
				LOC8 = 0;
				LOC8 = nsuCmpIgnoreStyle(id, k_156271);
				if (!(LOC8 == 0)) goto LA9;
				result = ((NU8) 9);
				goto BeforeRet;
			}
			LA9: ;
			{
				if (!(67 <= ((NI) (i_156402)))) goto LA13;
				goto LA5;
			}
			LA13: ;
			i_156402 += 1;
		} LA5: ;
	}
	LA3: ;
	result = ((NU8) 8);
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, nimnumberpostfix_156412)(tgeneraltokenizer156015* g, NI position) {
	NI result;
	NI pos;
	result = 0;
	pos = position;
	{
		if (!((NU8)((*g).Buf[pos]) == (NU8)(39))) goto LA3;
		pos += 1;
		switch (((NU8)((*g).Buf[pos]))) {
		case 102:
		case 70:
		{
			(*g).Kind = ((NU8) 7);
			pos += 1;
			{
				if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)))) goto LA8;
				pos += 1;
			}
			LA8: ;
			{
				if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)))) goto LA12;
				pos += 1;
			}
			LA12: ;
		}
		break;
		case 105:
		case 73:
		{
			pos += 1;
			{
				if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)))) goto LA17;
				pos += 1;
			}
			LA17: ;
			{
				if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)))) goto LA21;
				pos += 1;
			}
			LA21: ;
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA3: ;
	result = pos;
	return result;
}

N_NIMCALL(NI, nimnumber_156565)(tgeneraltokenizer156015* g, NI position) {
	NI result;
	NI pos;
	result = 0;
	pos = position;
	(*g).Kind = ((NU8) 3);
	while (1) {
		if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)))) goto LA1;
		pos += 1;
	} LA1: ;
	{
		if (!((NU8)((*g).Buf[pos]) == (NU8)(46))) goto LA4;
		(*g).Kind = ((NU8) 7);
		pos += 1;
		while (1) {
			if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)))) goto LA6;
			pos += 1;
		} LA6: ;
	}
	LA4: ;
	{
		if (!(((NU8)((*g).Buf[pos])) == ((NU8)(101)) || ((NU8)((*g).Buf[pos])) == ((NU8)(69)))) goto LA9;
		(*g).Kind = ((NU8) 7);
		pos += 1;
		{
			if (!(((NU8)((*g).Buf[pos])) == ((NU8)(43)) || ((NU8)((*g).Buf[pos])) == ((NU8)(45)))) goto LA13;
			pos += 1;
		}
		LA13: ;
		while (1) {
			if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)))) goto LA15;
			pos += 1;
		} LA15: ;
	}
	LA9: ;
	result = nimnumberpostfix_156412(g, pos);
	return result;
}

N_NIMCALL(void, nimnexttoken_156733)(tgeneraltokenizer156015* g) {
	NI pos;
	pos = (*g).Pos;
	(*g).Start = (*g).Pos;
	{
		if (!((*g).State == ((NU8) 10))) goto LA3;
		(*g).Kind = ((NU8) 10);
		while (1) {
			switch (((NU8)((*g).Buf[pos]))) {
			case 92:
			{
				(*g).Kind = ((NU8) 13);
				pos += 1;
				switch (((NU8)((*g).Buf[pos]))) {
				case 120:
				case 88:
				{
					pos += 1;
					{
						if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(70)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(102)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)))) goto LA10;
						pos += 1;
					}
					LA10: ;
					{
						if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(70)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(102)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)))) goto LA14;
						pos += 1;
					}
					LA14: ;
				}
				break;
				case 48 ... 57:
				{
					while (1) {
						if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)))) goto LA17;
						pos += 1;
					} LA17: ;
				}
				break;
				case 0:
				{
					(*g).State = ((NU8) 1);
				}
				break;
				default:
				{
					pos += 1;
				}
				break;
				}
				goto LA5;
			}
			break;
			case 0:
			case 13:
			case 10:
			{
				(*g).State = ((NU8) 1);
				goto LA5;
			}
			break;
			case 34:
			{
				pos += 1;
				(*g).State = ((NU8) 1);
				goto LA5;
			}
			break;
			default:
			{
				pos += 1;
			}
			break;
			}
		} LA5: ;
	}
	goto LA1;
	LA3: ;
	{
		switch (((NU8)((*g).Buf[pos]))) {
		case 32:
		case 9 ... 13:
		{
			(*g).Kind = ((NU8) 2);
			while (1) {
				if (!(((NU8)((*g).Buf[pos])) == ((NU8)(32)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(9)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(13)))) goto LA25;
				pos += 1;
			} LA25: ;
		}
		break;
		case 35:
		{
			(*g).Kind = ((NU8) 16);
			while (1) {
				if (!!((((NU8)((*g).Buf[pos])) == ((NU8)(0)) || ((NU8)((*g).Buf[pos])) == ((NU8)(10)) || ((NU8)((*g).Buf[pos])) == ((NU8)(13))))) goto LA27;
				pos += 1;
			} LA27: ;
		}
		break;
		case 97 ... 122:
		case 65 ... 90:
		case 95:
		case 128 ... 255:
		{
			NimStringDesc* id;
			id = copyString(((NimStringDesc*) &TMP478));
			while (1) {
				if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(90)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(122)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(128)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(255)))) goto LA29;
				id = addChar(id, (*g).Buf[pos]);
				pos += 1;
			} LA29: ;
			{
				if (!((NU8)((*g).Buf[pos]) == (NU8)(34))) goto LA32;
				{
					NIM_BOOL LOC36;
					LOC36 = 0;
					LOC36 = ((NU8)((*g).Buf[(NI64)(pos + 1)]) == (NU8)(34));
					if (!(LOC36)) goto LA37;
					LOC36 = ((NU8)((*g).Buf[(NI64)(pos + 2)]) == (NU8)(34));
					LA37: ;
					if (!LOC36) goto LA38;
					pos += 3;
					(*g).Kind = ((NU8) 11);
					while (1) {
						switch (((NU8)((*g).Buf[pos]))) {
						case 0:
						{
							goto LA40;
						}
						break;
						case 34:
						{
							pos += 1;
							{
								NIM_BOOL LOC45;
								NIM_BOOL LOC46;
								LOC45 = 0;
								LOC46 = 0;
								LOC46 = ((NU8)((*g).Buf[pos]) == (NU8)(34));
								if (!(LOC46)) goto LA47;
								LOC46 = ((NU8)((*g).Buf[(NI64)(pos + 1)]) == (NU8)(34));
								LA47: ;
								LOC45 = LOC46;
								if (!(LOC45)) goto LA48;
								LOC45 = !(((NU8)((*g).Buf[(NI64)(pos + 2)]) == (NU8)(34)));
								LA48: ;
								if (!LOC45) goto LA49;
								pos += 2;
								goto LA40;
							}
							LA49: ;
						}
						break;
						default:
						{
							pos += 1;
						}
						break;
						}
					} LA40: ;
				}
				goto LA34;
				LA38: ;
				{
					(*g).Kind = ((NU8) 23);
					pos += 1;
					while (1) {
						if (!!((((NU8)((*g).Buf[pos])) == ((NU8)(0)) || ((NU8)((*g).Buf[pos])) == ((NU8)(10)) || ((NU8)((*g).Buf[pos])) == ((NU8)(13))))) goto LA53;
						{
							NIM_BOOL LOC56;
							LOC56 = 0;
							LOC56 = ((NU8)((*g).Buf[pos]) == (NU8)(34));
							if (!(LOC56)) goto LA57;
							LOC56 = !(((NU8)((*g).Buf[(NI64)(pos + 1)]) == (NU8)(34)));
							LA57: ;
							if (!LOC56) goto LA58;
							goto LA53;
						}
						LA58: ;
						pos += 1;
					} LA53: ;
					{
						if (!((NU8)((*g).Buf[pos]) == (NU8)(34))) goto LA62;
						pos += 1;
					}
					LA62: ;
				}
				LA34: ;
			}
			goto LA30;
			LA32: ;
			{
				(*g).Kind = nimgetkeyword_156225(id);
			}
			LA30: ;
		}
		break;
		case 48:
		{
			pos += 1;
			switch (((NU8)((*g).Buf[pos]))) {
			case 98:
			case 66:
			{
				pos += 1;
				while (1) {
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(49)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)))) goto LA67;
					pos += 1;
				} LA67: ;
				pos = nimnumberpostfix_156412(g, pos);
			}
			break;
			case 120:
			case 88:
			{
				pos += 1;
				while (1) {
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(70)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(102)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)))) goto LA69;
					pos += 1;
				} LA69: ;
				pos = nimnumberpostfix_156412(g, pos);
			}
			break;
			case 111:
			case 79:
			{
				pos += 1;
				while (1) {
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(55)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)))) goto LA71;
					pos += 1;
				} LA71: ;
				pos = nimnumberpostfix_156412(g, pos);
			}
			break;
			default:
			{
				pos = nimnumber_156565(g, pos);
			}
			break;
			}
		}
		break;
		case 49 ... 57:
		{
			pos = nimnumber_156565(g, pos);
		}
		break;
		case 39:
		{
			pos += 1;
			(*g).Kind = ((NU8) 12);
			while (1) {
				switch (((NU8)((*g).Buf[pos]))) {
				case 0:
				case 13:
				case 10:
				{
					goto LA75;
				}
				break;
				case 39:
				{
					pos += 1;
					goto LA75;
				}
				break;
				case 92:
				{
					pos += 2;
				}
				break;
				default:
				{
					pos += 1;
				}
				break;
				}
			} LA75: ;
		}
		break;
		case 34:
		{
			pos += 1;
			{
				NIM_BOOL LOC83;
				LOC83 = 0;
				LOC83 = ((NU8)((*g).Buf[pos]) == (NU8)(34));
				if (!(LOC83)) goto LA84;
				LOC83 = ((NU8)((*g).Buf[(NI64)(pos + 1)]) == (NU8)(34));
				LA84: ;
				if (!LOC83) goto LA85;
				pos += 2;
				(*g).Kind = ((NU8) 11);
				while (1) {
					switch (((NU8)((*g).Buf[pos]))) {
					case 0:
					{
						goto LA87;
					}
					break;
					case 34:
					{
						pos += 1;
						{
							NIM_BOOL LOC92;
							NIM_BOOL LOC93;
							LOC92 = 0;
							LOC93 = 0;
							LOC93 = ((NU8)((*g).Buf[pos]) == (NU8)(34));
							if (!(LOC93)) goto LA94;
							LOC93 = ((NU8)((*g).Buf[(NI64)(pos + 1)]) == (NU8)(34));
							LA94: ;
							LOC92 = LOC93;
							if (!(LOC92)) goto LA95;
							LOC92 = !(((NU8)((*g).Buf[(NI64)(pos + 2)]) == (NU8)(34)));
							LA95: ;
							if (!LOC92) goto LA96;
							pos += 2;
							goto LA87;
						}
						LA96: ;
					}
					break;
					default:
					{
						pos += 1;
					}
					break;
					}
				} LA87: ;
			}
			goto LA81;
			LA85: ;
			{
				(*g).Kind = ((NU8) 10);
				while (1) {
					switch (((NU8)((*g).Buf[pos]))) {
					case 0:
					case 13:
					case 10:
					{
						goto LA100;
					}
					break;
					case 34:
					{
						pos += 1;
						goto LA100;
					}
					break;
					case 92:
					{
						(*g).State = (*g).Kind;
						goto LA100;
					}
					break;
					default:
					{
						pos += 1;
					}
					break;
					}
				} LA100: ;
			}
			LA81: ;
		}
		break;
		case 40:
		case 41:
		case 91:
		case 93:
		case 123:
		case 125:
		case 96:
		case 58:
		case 44:
		case 59:
		{
			pos += 1;
			(*g).Kind = ((NU8) 15);
		}
		break;
		case 0:
		{
			(*g).Kind = ((NU8) 0);
		}
		break;
		default:
		{
			{
				if (!((TMP547[((NU8)((*g).Buf[pos]))/8] &(1<<(((NU8)((*g).Buf[pos]))%8)))!=0)) goto LA110;
				(*g).Kind = ((NU8) 14);
				while (1) {
					if (!((TMP547[((NU8)((*g).Buf[pos]))/8] &(1<<(((NU8)((*g).Buf[pos]))%8)))!=0)) goto LA112;
					pos += 1;
				} LA112: ;
			}
			goto LA108;
			LA110: ;
			{
				pos += 1;
				(*g).Kind = ((NU8) 1);
			}
			LA108: ;
		}
		break;
		}
	}
	LA1: ;
	(*g).Length = (NI64)(pos - (*g).Pos);
	{
		NIM_BOOL LOC116;
		LOC116 = 0;
		LOC116 = !(((*g).Kind == ((NU8) 0)));
		if (!(LOC116)) goto LA117;
		LOC116 = ((*g).Length <= 0);
		LA117: ;
		if (!LOC116) goto LA118;
	}
	LA118: ;
	(*g).Pos = pos;
}

N_NIMCALL(NI, iskeyword_157983)(NimStringDesc** x, NI xLen0, NimStringDesc* y) {
	NI result;
	NI a;
	NI b;
	result = 0;
	a = 0;
	b = (NI64)(xLen0 - 1);
	while (1) {
		NI mid;
		NI c;
		if (!(a <= b)) goto LA1;
		mid = (NI64)((NI64)(a + b) / 2);
		c = cmp_4148(x[mid], y);
		{
			if (!(c < 0)) goto LA4;
			a = (NI64)(mid + 1);
		}
		goto LA2;
		LA4: ;
		{
			if (!(0 < c)) goto LA7;
			b = (NI64)(mid - 1);
		}
		goto LA2;
		LA7: ;
		{
			result = mid;
			goto BeforeRet;
		}
		LA2: ;
	} LA1: ;
	result = -1;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, generalnumber_157649)(tgeneraltokenizer156015* g, NI position) {
	NI result;
	NI pos;
	result = 0;
	pos = position;
	(*g).Kind = ((NU8) 3);
	while (1) {
		if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)))) goto LA1;
		pos += 1;
	} LA1: ;
	{
		if (!((NU8)((*g).Buf[pos]) == (NU8)(46))) goto LA4;
		(*g).Kind = ((NU8) 7);
		pos += 1;
		while (1) {
			if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)))) goto LA6;
			pos += 1;
		} LA6: ;
	}
	LA4: ;
	{
		if (!(((NU8)((*g).Buf[pos])) == ((NU8)(101)) || ((NU8)((*g).Buf[pos])) == ((NU8)(69)))) goto LA9;
		(*g).Kind = ((NU8) 7);
		pos += 1;
		{
			if (!(((NU8)((*g).Buf[pos])) == ((NU8)(43)) || ((NU8)((*g).Buf[pos])) == ((NU8)(45)))) goto LA13;
			pos += 1;
		}
		LA13: ;
		while (1) {
			if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)))) goto LA15;
			pos += 1;
		} LA15: ;
	}
	LA9: ;
	result = pos;
	return result;
}

N_NIMCALL(NI, generalstrlit_157812)(tgeneraltokenizer156015* g, NI position) {
	NI result;
	NI pos;
	NIM_CHAR c;
	result = 0;
	pos = position;
	(*g).Kind = ((NU8) 10);
	c = (*g).Buf[pos];
	pos += 1;
	while (1) {
		switch (((NU8)((*g).Buf[pos]))) {
		case 0:
		{
			goto LA1;
		}
		break;
		case 92:
		{
			pos += 1;
			switch (((NU8)((*g).Buf[pos]))) {
			case 0:
			{
				goto LA1;
			}
			break;
			case 48 ... 57:
			{
				while (1) {
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)))) goto LA6;
					pos += 1;
				} LA6: ;
			}
			break;
			case 120:
			case 88:
			{
				pos += 1;
				{
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(70)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(102)))) goto LA10;
					pos += 1;
				}
				LA10: ;
				{
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(70)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(102)))) goto LA14;
					pos += 1;
				}
				LA14: ;
			}
			break;
			default:
			{
				pos += 2;
			}
			break;
			}
		}
		break;
		default:
		{
			{
				if (!((NU8)((*g).Buf[pos]) == (NU8)(c))) goto LA20;
				pos += 1;
				goto LA1;
			}
			goto LA18;
			LA20: ;
			{
				pos += 1;
			}
			LA18: ;
		}
		break;
		}
	} LA1: ;
	result = pos;
	return result;
}

N_NIMCALL(void, clikenexttoken_158048)(tgeneraltokenizer156015* g, NimStringDesc** keywords, NI keywordsLen0, NU8 flags) {
	NI pos;
	pos = (*g).Pos;
	(*g).Start = (*g).Pos;
	{
		if (!((*g).State == ((NU8) 10))) goto LA3;
		(*g).Kind = ((NU8) 10);
		while (1) {
			switch (((NU8)((*g).Buf[pos]))) {
			case 92:
			{
				(*g).Kind = ((NU8) 13);
				pos += 1;
				switch (((NU8)((*g).Buf[pos]))) {
				case 120:
				case 88:
				{
					pos += 1;
					{
						if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(70)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(102)))) goto LA10;
						pos += 1;
					}
					LA10: ;
					{
						if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(70)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(102)))) goto LA14;
						pos += 1;
					}
					LA14: ;
				}
				break;
				case 48 ... 57:
				{
					while (1) {
						if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)))) goto LA17;
						pos += 1;
					} LA17: ;
				}
				break;
				case 0:
				{
					(*g).State = ((NU8) 1);
				}
				break;
				default:
				{
					pos += 1;
				}
				break;
				}
				goto LA5;
			}
			break;
			case 0:
			case 13:
			case 10:
			{
				(*g).State = ((NU8) 1);
				goto LA5;
			}
			break;
			case 34:
			{
				pos += 1;
				(*g).State = ((NU8) 1);
				goto LA5;
			}
			break;
			default:
			{
				pos += 1;
			}
			break;
			}
		} LA5: ;
	}
	goto LA1;
	LA3: ;
	{
		switch (((NU8)((*g).Buf[pos]))) {
		case 32:
		case 9 ... 13:
		{
			(*g).Kind = ((NU8) 2);
			while (1) {
				if (!(((NU8)((*g).Buf[pos])) == ((NU8)(32)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(9)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(13)))) goto LA25;
				pos += 1;
			} LA25: ;
		}
		break;
		case 47:
		{
			pos += 1;
			{
				if (!((NU8)((*g).Buf[pos]) == (NU8)(47))) goto LA29;
				(*g).Kind = ((NU8) 16);
				while (1) {
					if (!!((((NU8)((*g).Buf[pos])) == ((NU8)(0)) || ((NU8)((*g).Buf[pos])) == ((NU8)(10)) || ((NU8)((*g).Buf[pos])) == ((NU8)(13))))) goto LA31;
					pos += 1;
				} LA31: ;
			}
			goto LA27;
			LA29: ;
			{
				NI nested;
				if (!((NU8)((*g).Buf[pos]) == (NU8)(42))) goto LA33;
				(*g).Kind = ((NU8) 17);
				nested = 0;
				pos += 1;
				while (1) {
					switch (((NU8)((*g).Buf[pos]))) {
					case 42:
					{
						pos += 1;
						{
							if (!((NU8)((*g).Buf[pos]) == (NU8)(47))) goto LA39;
							pos += 1;
							{
								if (!(nested == 0)) goto LA43;
								goto LA35;
							}
							LA43: ;
						}
						LA39: ;
					}
					break;
					case 47:
					{
						pos += 1;
						{
							if (!((NU8)((*g).Buf[pos]) == (NU8)(42))) goto LA48;
							pos += 1;
							{
								if (!((flags &(1<<((((NU8) 1))&7)))!=0)) goto LA52;
								nested += 1;
							}
							LA52: ;
						}
						LA48: ;
					}
					break;
					case 0:
					{
						goto LA35;
					}
					break;
					default:
					{
						pos += 1;
					}
					break;
					}
				} LA35: ;
			}
			goto LA27;
			LA33: ;
			LA27: ;
		}
		break;
		case 35:
		{
			pos += 1;
			{
				if (!((flags &(1<<((((NU8) 0))&7)))!=0)) goto LA59;
				(*g).Kind = ((NU8) 25);
				while (1) {
					if (!(((NU8)((*g).Buf[pos])) == ((NU8)(32)) || ((NU8)((*g).Buf[pos])) == ((NU8)(9)))) goto LA61;
					pos += 1;
				} LA61: ;
				while (1) {
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(90)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(122)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(128)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(255)))) goto LA62;
					pos += 1;
				} LA62: ;
			}
			goto LA57;
			LA59: ;
			{
				(*g).Kind = ((NU8) 14);
			}
			LA57: ;
		}
		break;
		case 97 ... 122:
		case 65 ... 90:
		case 95:
		case 128 ... 255:
		{
			NimStringDesc* id;
			id = copyString(((NimStringDesc*) &TMP478));
			while (1) {
				if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(90)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(122)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) == ((NU8)(95)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(128)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(255)))) goto LA65;
				id = addChar(id, (*g).Buf[pos]);
				pos += 1;
			} LA65: ;
			{
				NI LOC68;
				LOC68 = 0;
				LOC68 = iskeyword_157983(keywords, keywordsLen0, id);
				if (!(0 <= LOC68)) goto LA69;
				(*g).Kind = ((NU8) 9);
			}
			goto LA66;
			LA69: ;
			{
				(*g).Kind = ((NU8) 8);
			}
			LA66: ;
		}
		break;
		case 48:
		{
			pos += 1;
			switch (((NU8)((*g).Buf[pos]))) {
			case 98:
			case 66:
			{
				pos += 1;
				while (1) {
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(49)))) goto LA74;
					pos += 1;
				} LA74: ;
				{
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(90)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(122)))) goto LA77;
					pos += 1;
				}
				LA77: ;
			}
			break;
			case 120:
			case 88:
			{
				pos += 1;
				while (1) {
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(57)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(70)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(102)))) goto LA80;
					pos += 1;
				} LA80: ;
				{
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(90)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(122)))) goto LA83;
					pos += 1;
				}
				LA83: ;
			}
			break;
			case 48 ... 55:
			{
				pos += 1;
				while (1) {
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(48)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(55)))) goto LA86;
					pos += 1;
				} LA86: ;
				{
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(90)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(122)))) goto LA89;
					pos += 1;
				}
				LA89: ;
			}
			break;
			default:
			{
				pos = generalnumber_157649(g, pos);
				{
					if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(90)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(122)))) goto LA94;
					pos += 1;
				}
				LA94: ;
			}
			break;
			}
		}
		break;
		case 49 ... 57:
		{
			pos = generalnumber_157649(g, pos);
			{
				if (!(((NU8)((*g).Buf[pos])) >= ((NU8)(65)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(90)) || ((NU8)((*g).Buf[pos])) >= ((NU8)(97)) && ((NU8)((*g).Buf[pos])) <= ((NU8)(122)))) goto LA99;
				pos += 1;
			}
			LA99: ;
		}
		break;
		case 39:
		{
			pos = generalstrlit_157812(g, pos);
			(*g).Kind = ((NU8) 12);
		}
		break;
		case 34:
		{
			pos += 1;
			(*g).Kind = ((NU8) 10);
			while (1) {
				switch (((NU8)((*g).Buf[pos]))) {
				case 0:
				{
					goto LA103;
				}
				break;
				case 34:
				{
					pos += 1;
					goto LA103;
				}
				break;
				case 92:
				{
					(*g).State = (*g).Kind;
					goto LA103;
				}
				break;
				default:
				{
					pos += 1;
				}
				break;
				}
			} LA103: ;
		}
		break;
		case 40:
		case 41:
		case 91:
		case 93:
		case 123:
		case 125:
		case 58:
		case 44:
		case 59:
		case 46:
		{
			pos += 1;
			(*g).Kind = ((NU8) 15);
		}
		break;
		case 0:
		{
			(*g).Kind = ((NU8) 0);
		}
		break;
		default:
		{
			{
				if (!((TMP547[((NU8)((*g).Buf[pos]))/8] &(1<<(((NU8)((*g).Buf[pos]))%8)))!=0)) goto LA113;
				(*g).Kind = ((NU8) 14);
				while (1) {
					if (!((TMP547[((NU8)((*g).Buf[pos]))/8] &(1<<(((NU8)((*g).Buf[pos]))%8)))!=0)) goto LA115;
					pos += 1;
				} LA115: ;
			}
			goto LA111;
			LA113: ;
			{
				pos += 1;
				(*g).Kind = ((NU8) 1);
			}
			LA111: ;
		}
		break;
		}
	}
	LA1: ;
	(*g).Length = (NI64)(pos - (*g).Pos);
	{
		NIM_BOOL LOC119;
		LOC119 = 0;
		LOC119 = !(((*g).Kind == ((NU8) 0)));
		if (!(LOC119)) goto LA120;
		LOC119 = ((*g).Length <= 0);
		LA120: ;
		if (!LOC119) goto LA121;
	}
	LA121: ;
	(*g).Pos = pos;
}

N_NIMCALL(void, cppnexttoken_159062)(tgeneraltokenizer156015* g) {
	clikenexttoken_158048(g, TMP548, 48, 1);
}

N_NIMCALL(void, csharpnexttoken_159079)(tgeneraltokenizer156015* g) {
	clikenexttoken_158048(g, TMP582, 77, 1);
}

N_NIMCALL(void, cnexttoken_159046)(tgeneraltokenizer156015* g) {
	clikenexttoken_158048(g, TMP614, 37, 1);
}

N_NIMCALL(void, javanexttoken_159096)(tgeneraltokenizer156015* g) {
	clikenexttoken_158048(g, TMP619, 53, 0);
}

N_NIMCALL(void, getnexttoken_159114)(tgeneraltokenizer156015* g, NU8 lang) {
	switch (lang) {
	case ((NU8) 0):
	{
	}
	break;
	case ((NU8) 1):
	{
		nimnexttoken_156733(g);
	}
	break;
	case ((NU8) 2):
	{
		cppnexttoken_159062(g);
	}
	break;
	case ((NU8) 3):
	{
		csharpnexttoken_159079(g);
	}
	break;
	case ((NU8) 4):
	{
		cnexttoken_159046(g);
	}
	break;
	case ((NU8) 5):
	{
		javanexttoken_159096(g);
	}
	break;
	}
}

N_NIMCALL(void, deinitgeneraltokenizer_156215)(tgeneraltokenizer156015* g) {
}
N_NOINLINE(void, HEX00_highliteInit)(void) {
}

N_NOINLINE(void, HEX00_highliteDatInit)(void) {
static TNimNode* TMP474[6];
static TNimNode* TMP475[33];
NI TMP477;
static char* NIM_CONST TMP476[33] = {
"gtEof", 
"gtNone", 
"gtWhitespace", 
"gtDecNumber", 
"gtBinNumber", 
"gtHexNumber", 
"gtOctNumber", 
"gtFloatNumber", 
"gtIdentifier", 
"gtKeyword", 
"gtStringLit", 
"gtLongStringLit", 
"gtCharLit", 
"gtEscapeSequence", 
"gtOperator", 
"gtPunctuation", 
"gtComment", 
"gtLongComment", 
"gtRegularExpression", 
"gtTagStart", 
"gtTagEnd", 
"gtKey", 
"gtValue", 
"gtRawData", 
"gtAssembler", 
"gtPreprocessor", 
"gtDirective", 
"gtCommand", 
"gtRule", 
"gtHyperlink", 
"gtLabel", 
"gtReference", 
"gtOther"};
static TNimNode TMP35[41];
NTI156015.size = sizeof(tgeneraltokenizer156015);
NTI156015.kind = 17;
NTI156015.base = (&NTI2811);
NTI156015.flags = 1;
TMP474[0] = &TMP35[1];
NTI156013.size = sizeof(NU8);
NTI156013.kind = 14;
NTI156013.base = 0;
NTI156013.flags = 3;
for (TMP477 = 0; TMP477 < 33; TMP477++) {
TMP35[TMP477+2].kind = 1;
TMP35[TMP477+2].offset = TMP477;
TMP35[TMP477+2].name = TMP476[TMP477];
TMP475[TMP477] = &TMP35[TMP477+2];
}
TMP35[35].len = 33; TMP35[35].kind = 2; TMP35[35].sons = &TMP475[0];
NTI156013.node = &TMP35[35];
TMP35[1].kind = 1;
TMP35[1].offset = offsetof(tgeneraltokenizer156015, Kind);
TMP35[1].typ = (&NTI156013);
TMP35[1].name = "kind";
TMP474[1] = &TMP35[36];
TMP35[36].kind = 1;
TMP35[36].offset = offsetof(tgeneraltokenizer156015, Start);
TMP35[36].typ = (&NTI112);
TMP35[36].name = "start";
TMP474[2] = &TMP35[37];
TMP35[37].kind = 1;
TMP35[37].offset = offsetof(tgeneraltokenizer156015, Length);
TMP35[37].typ = (&NTI112);
TMP35[37].name = "length";
TMP474[3] = &TMP35[38];
TMP35[38].kind = 1;
TMP35[38].offset = offsetof(tgeneraltokenizer156015, Buf);
TMP35[38].typ = (&NTI159);
TMP35[38].name = "buf";
TMP474[4] = &TMP35[39];
TMP35[39].kind = 1;
TMP35[39].offset = offsetof(tgeneraltokenizer156015, Pos);
TMP35[39].typ = (&NTI112);
TMP35[39].name = "pos";
TMP474[5] = &TMP35[40];
TMP35[40].kind = 1;
TMP35[40].offset = offsetof(tgeneraltokenizer156015, State);
TMP35[40].typ = (&NTI156013);
TMP35[40].name = "state";
TMP35[0].len = 6; TMP35[0].kind = 2; TMP35[0].sons = &TMP474[0];
NTI156015.node = &TMP35[0];
}

