/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>

#include <string.h>
typedef struct tlogger133024 tlogger133024;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tconsolelogger133026 tconsolelogger133026;
typedef struct TY100259 TY100259;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tfilelogger133028 tfilelogger133028;
typedef struct trollingfilelogger133030 trollingfilelogger133030;
typedef struct TY133250 TY133250;
typedef struct tcell38448 tcell38448;
typedef struct tcellseq38464 tcellseq38464;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38460 tcellset38460;
typedef struct tpagedesc38456 tpagedesc38456;
typedef struct tmemregion21810 tmemregion21810;
typedef struct tsmallchunk21038 tsmallchunk21038;
typedef struct tllchunk21804 tllchunk21804;
typedef struct tbigchunk21040 tbigchunk21040;
typedef struct tintset21015 tintset21015;
typedef struct ttrunk21011 ttrunk21011;
typedef struct tavlnode21808 tavlnode21808;
typedef struct tgcstat40414 tgcstat40414;
typedef struct tbasechunk21036 tbasechunk21036;
typedef struct tfreecell21028 tfreecell21028;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef NimStringDesc* TY133122[4];
typedef NimStringDesc* TY133016[7];
struct TY100259 {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct tlogger133024 {
  TNimObject Sup;
NU8 Levelthreshold;
NimStringDesc* Fmtstr;
};
struct tconsolelogger133026 {
  tlogger133024 Sup;
};
struct tfilelogger133028 {
  tlogger133024 Sup;
FILE* F;
};
struct trollingfilelogger133030 {
  tfilelogger133028 Sup;
NI Maxlines;
NI Curline;
NimStringDesc* Basename;
NI Logfiles;
};
typedef NimStringDesc* TY133244[3];
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38448 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38464 {
NI Len;
NI Cap;
tcell38448** D;
};
struct tcellset38460 {
NI Counter;
NI Max;
tpagedesc38456* Head;
tpagedesc38456** Data;
};
typedef tsmallchunk21038* TY21822[512];
typedef ttrunk21011* ttrunkbuckets21013[256];
struct tintset21015 {
ttrunkbuckets21013 Data;
};
struct tmemregion21810 {
NI Minlargeobj;
NI Maxlargeobj;
TY21822 Freesmallchunks;
tllchunk21804* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21040* Freechunkslist;
tintset21015 Chunkstarts;
tavlnode21808* Root;
tavlnode21808* Deleted;
tavlnode21808* Last;
tavlnode21808* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38464 Zct;
tcellseq38464 Decstack;
tcellset38460 Cycleroots;
tcellseq38464 Tempstack;
NI Recgclock;
tmemregion21810 Region;
tgcstat40414 Stat;
};
typedef NI TY21018[8];
struct tpagedesc38456 {
tpagedesc38456* Next;
NI Key;
TY21018 Bits;
};
struct tbasechunk21036 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21038 {
  tbasechunk21036 Sup;
tsmallchunk21038* Next;
tsmallchunk21038* Prev;
tfreecell21028* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk21804 {
NI Size;
NI Acc;
tllchunk21804* Next;
};
struct tbigchunk21040 {
  tbasechunk21036 Sup;
tbigchunk21040* Next;
tbigchunk21040* Prev;
NI Align;
NF Data;
};
struct ttrunk21011 {
ttrunk21011* Next;
NI Key;
TY21018 Bits;
};
typedef tavlnode21808* TY21814[2];
struct tavlnode21808 {
TY21814 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21028 {
tfreecell21028* Next;
NI Zerofield;
};
struct TY133250 {
  TGenericSeq Sup;
  tlogger133024* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, log_133091)(tlogger133024* l, NU8 level, NimStringDesc* frmt, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, log_133104)(tconsolelogger133026* l, NU8 level, NimStringDesc* frmt, NimStringDesc** args, NI argsLen0);
static N_INLINE(void, writeln_112651)(FILE* f, NimStringDesc** x, NI xLen0);
N_NIMCALL(void, write_9259)(FILE* f, NimStringDesc* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, substitutelog_133039)(NimStringDesc* frmt);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY100259* Result);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(void, log_133126)(tfilelogger133028* l, NU8 level, NimStringDesc* frmt, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, log_133226)(trollingfilelogger133030* l, NU8 level, NimStringDesc* frmt, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP83)(void* p, NI op);
N_NIMCALL(void, TMP84)(void* p, NI op);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38448*, usrtocell_41839)(void* usr);
static N_INLINE(void, rtladdzct_43402)(tcell38448* c);
N_NOINLINE(void, addzct_41815)(tcellseq38464* s, tcell38448* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void, log_133101)(tlogger133024* l, NU8 level, NimStringDesc* frmt, NimStringDesc** args, NI argsLen0);
STRING_LITERAL(TMP49, "\012", 1);
STRING_LITERAL(TMP50, "DEBUG", 5);
STRING_LITERAL(TMP51, "INFO", 4);
STRING_LITERAL(TMP52, "WARN", 4);
STRING_LITERAL(TMP53, "ERROR", 5);
STRING_LITERAL(TMP54, "FATAL", 5);
STRING_LITERAL(TMP55, "NONE", 4);
NIM_CONST TY133016 levelnames_133015 = {((NimStringDesc*) &TMP50),
((NimStringDesc*) &TMP50),
((NimStringDesc*) &TMP51),
((NimStringDesc*) &TMP52),
((NimStringDesc*) &TMP53),
((NimStringDesc*) &TMP54),
((NimStringDesc*) &TMP55)}
;
STRING_LITERAL(TMP56, " ", 1);
STRING_LITERAL(TMP57, "", 0);
STRING_LITERAL(TMP61, "date", 4);
STRING_LITERAL(TMP62, "time", 4);
STRING_LITERAL(TMP63, "app", 3);
STRING_LITERAL(TMP64, "appdir", 6);
STRING_LITERAL(TMP65, "appname", 7);
NU8 level_133249;
TY133250* handlers_133269;
extern TNimType NTI1009; /* TObject */
TNimType NTI133024; /* TLogger */
TNimType NTI133006; /* TLevel */
extern TNimType NTI142; /* string */
TNimType NTI133093; /* ref TLogger */
TNimType NTI133250; /* seq[ref TLogger] */
extern tgcheap40416 gch_40444;
TNimType NTI133028; /* TFileLogger */
extern TNimType NTI9004; /* TFile */
TNimType NTI133030; /* TRollingFileLogger */
extern TNimType NTI105; /* int */
TNimType NTI133026; /* TConsoleLogger */

N_NIMCALL(void, log_133091)(tlogger133024* l, NU8 level, NimStringDesc* frmt, NimStringDesc** args, NI argsLen0) {
}
static N_INLINE(void, writeln_112651)(FILE* f, NimStringDesc** x, NI xLen0) {
	NimStringDesc* i_112665;
	NI i_112671;
	i_112665 = 0;
	i_112671 = 0;
	while (1) {
		if (!(i_112671 < xLen0)) goto LA1;
		i_112665 = x[i_112671];
		write_9259(f, i_112665);		i_112671 += 1;
	} LA1: ;
	write_9259(f, ((NimStringDesc*) &TMP49));}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;	return result;
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));	(*dest).Sup.len += (*src).Sup.len;
}
N_NIMCALL(NimStringDesc*, substitutelog_133039)(NimStringDesc* frmt) {
	NimStringDesc* result;
	NI i;
	result = 0;
	result = rawNewString((NI64)(frmt->Sup.len + 20));
	i = 0;
	while (1) {
		if (!(i < frmt->Sup.len)) goto LA1;
		{
			if (!!(((NU8)(frmt->data[i]) == (NU8)(36)))) goto LA4;
			result = addChar(result, frmt->data[i]);
			i += 1;
		}		goto LA2;
		LA4: ;
		{
			NimStringDesc* v;
			NimStringDesc* app;
			i += 1;
			v = copyString(((NimStringDesc*) &TMP57));
			app = nosgetAppFilename();
			while (1) {
				NIM_CHAR LOC8;
				if (!(((NU8)(frmt->data[i])) >= ((NU8)(97)) && ((NU8)(frmt->data[i])) <= ((NU8)(122)) || ((NU8)(frmt->data[i])) >= ((NU8)(65)) && ((NU8)(frmt->data[i])) <= ((NU8)(90)) || ((NU8)(frmt->data[i])) >= ((NU8)(48)) && ((NU8)(frmt->data[i])) <= ((NU8)(57)) || ((NU8)(frmt->data[i])) == ((NU8)(95)))) goto LA7;
				LOC8 = 0;
				LOC8 = nsuToLowerChar(frmt->data[i]);
				v = addChar(v, LOC8);
				i += 1;
			} LA7: ;
			if (eqStrings(v, ((NimStringDesc*) &TMP61))) goto LA9;
			if (eqStrings(v, ((NimStringDesc*) &TMP62))) goto LA10;
			if (eqStrings(v, ((NimStringDesc*) &TMP63))) goto LA11;
			if (eqStrings(v, ((NimStringDesc*) &TMP64))) goto LA12;
			if (eqStrings(v, ((NimStringDesc*) &TMP65))) goto LA13;
			goto LA14;
			LA9: ;
			{
				NimStringDesc* LOC17;
				LOC17 = 0;
				LOC17 = ntgetDateStr();
				result = resizeString(result, LOC17->Sup.len + 0);
appendString(result, LOC17);
			}			goto LA15;
			LA10: ;
			{
				NimStringDesc* LOC19;
				LOC19 = 0;
				LOC19 = ntgetClockStr();
				result = resizeString(result, LOC19->Sup.len + 0);
appendString(result, LOC19);
			}			goto LA15;
			LA11: ;
			{
				result = resizeString(result, app->Sup.len + 0);
appendString(result, app);
			}			goto LA15;
			LA12: ;
			{
				TY100259 LOC22;
				memset((void*)&LOC22, 0, sizeof(LOC22));
				nossplitFile(app, &LOC22);				result = resizeString(result, LOC22.Field0->Sup.len + 0);
appendString(result, LOC22.Field0);
			}			goto LA15;
			LA13: ;
			{
				TY100259 LOC24;
				memset((void*)&LOC24, 0, sizeof(LOC24));
				nossplitFile(app, &LOC24);				result = resizeString(result, LOC24.Field1->Sup.len + 0);
appendString(result, LOC24.Field1);
			}			goto LA15;
			LA14: ;
			{
			}			LA15: ;
		}		LA2: ;
	} LA1: ;
	return result;
}
N_NIMCALL(void, log_133104)(tconsolelogger133026* l, NU8 level, NimStringDesc* frmt, NimStringDesc** args, NI argsLen0) {
	TY133122 LOC1;
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = copyString(levelnames_133015[(level)- 0]);
	LOC1[1] = copyString(((NimStringDesc*) &TMP56));
	LOC1[2] = substitutelog_133039((*l).Sup.Fmtstr);
	LOC1[3] = nsuFormatOpenArray(frmt, args, argsLen0);
	writeln_112651(stdout, LOC1, 4);}
N_NIMCALL(void, log_133126)(tfilelogger133028* l, NU8 level, NimStringDesc* frmt, NimStringDesc** args, NI argsLen0) {
	TY133122 LOC1;
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = copyString(levelnames_133015[(level)- 0]);
	LOC1[1] = copyString(((NimStringDesc*) &TMP56));
	LOC1[2] = substitutelog_133039((*l).Sup.Fmtstr);
	LOC1[3] = nsuFormatOpenArray(frmt, args, argsLen0);
	writeln_112651((*l).F, LOC1, 4);}
N_NIMCALL(void, log_133226)(trollingfilelogger133030* l, NU8 level, NimStringDesc* frmt, NimStringDesc** args, NI argsLen0) {
	TY133244 LOC1;
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = copyString(levelnames_133015[(level)- 0]);
	LOC1[1] = copyString(((NimStringDesc*) &TMP56));
	LOC1[2] = nsuFormatOpenArray(frmt, args, argsLen0);
	writeln_112651((*l).Sup.F, LOC1, 3);}N_NIMCALL(void, TMP83)(void* p, NI op) {
	tlogger133024* a;
	a = (tlogger133024*)p;
	nimGCvisit((void*)(*a).Fmtstr, op);
}
N_NIMCALL(void, TMP84)(void* p, NI op) {
	TY133250* a;
	NI LOC1;
	a = (TY133250*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(tcell38448*, usrtocell_41839)(void* usr) {
	tcell38448* result;
	result = 0;
	result = ((tcell38448*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38448))))));
	return result;
}
static N_INLINE(void, rtladdzct_43402)(tcell38448* c) {
	addzct_41815(&gch_40444.Zct, c);}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38448* c;
	c = usrtocell_41839(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43402(c);	}	LA3: ;
}
N_NIMCALL(void, logloop_133272)(NU8 level, NimStringDesc* frmt, NimStringDesc** args, NI argsLen0) {
	tlogger133024* logger_133309;
	NI i_133319;
	logger_133309 = 0;
	i_133319 = 0;
	while (1) {
		if (!(i_133319 < handlers_133269->Sup.len)) goto LA1;
		logger_133309 = handlers_133269->data[i_133319];
		{
			if (!((*logger_133309).Levelthreshold <= level)) goto LA4;
			log_133101(logger_133309, level, frmt, args, argsLen0);		}		LA4: ;
		i_133319 += 1;
	} LA1: ;
}N_NOINLINE(void, nimloggingInit)(void) {
	level_133249 = ((NU8) 0);
	if (handlers_133269) nimGCunrefNoCycle(handlers_133269);
	handlers_133269 = (TY133250*) newSeqRC1((&NTI133250), 0);
}

N_NOINLINE(void, nimloggingDatInit)(void) {
static TNimNode* TMP79[2];
static TNimNode* TMP80[7];
NI TMP82;
static char* NIM_CONST TMP81[7] = {
"lvlAll", 
"lvlDebug", 
"lvlInfo", 
"lvlWarn", 
"lvlError", 
"lvlFatal", 
"lvlNone"};
static TNimNode* TMP755[4];
static TNimNode TMP42[18];
NTI133024.size = sizeof(tlogger133024);
NTI133024.kind = 17;
NTI133024.base = (&NTI1009);
NTI133024.flags = 2;
TMP79[0] = &TMP42[1];
NTI133006.size = sizeof(NU8);
NTI133006.kind = 14;
NTI133006.base = 0;
NTI133006.flags = 3;
for (TMP82 = 0; TMP82 < 7; TMP82++) {
TMP42[TMP82+2].kind = 1;
TMP42[TMP82+2].offset = TMP82;
TMP42[TMP82+2].name = TMP81[TMP82];
TMP80[TMP82] = &TMP42[TMP82+2];
}
TMP42[9].len = 7; TMP42[9].kind = 2; TMP42[9].sons = &TMP80[0];
NTI133006.node = &TMP42[9];
TMP42[1].kind = 1;
TMP42[1].offset = offsetof(tlogger133024, Levelthreshold);
TMP42[1].typ = (&NTI133006);
TMP42[1].name = "levelThreshold";
TMP79[1] = &TMP42[10];
TMP42[10].kind = 1;
TMP42[10].offset = offsetof(tlogger133024, Fmtstr);
TMP42[10].typ = (&NTI142);
TMP42[10].name = "fmtStr";
TMP42[0].len = 2; TMP42[0].kind = 2; TMP42[0].sons = &TMP79[0];
NTI133024.node = &TMP42[0];
NTI133093.size = sizeof(tlogger133024*);
NTI133093.kind = 22;
NTI133093.base = (&NTI133024);
NTI133093.flags = 2;
NTI133093.marker = TMP83;
NTI133250.size = sizeof(TY133250*);
NTI133250.kind = 24;
NTI133250.base = (&NTI133093);
NTI133250.flags = 2;
NTI133250.marker = TMP84;
NTI133028.size = sizeof(tfilelogger133028);
NTI133028.kind = 17;
NTI133028.base = (&NTI133024);
NTI133028.flags = 2;
TMP42[11].kind = 1;
TMP42[11].offset = offsetof(tfilelogger133028, F);
TMP42[11].typ = (&NTI9004);
TMP42[11].name = "f";
NTI133028.node = &TMP42[11];
NTI133030.size = sizeof(trollingfilelogger133030);
NTI133030.kind = 17;
NTI133030.base = (&NTI133028);
NTI133030.flags = 2;
TMP755[0] = &TMP42[13];
TMP42[13].kind = 1;
TMP42[13].offset = offsetof(trollingfilelogger133030, Maxlines);
TMP42[13].typ = (&NTI105);
TMP42[13].name = "maxLines";
TMP755[1] = &TMP42[14];
TMP42[14].kind = 1;
TMP42[14].offset = offsetof(trollingfilelogger133030, Curline);
TMP42[14].typ = (&NTI105);
TMP42[14].name = "curLine";
TMP755[2] = &TMP42[15];
TMP42[15].kind = 1;
TMP42[15].offset = offsetof(trollingfilelogger133030, Basename);
TMP42[15].typ = (&NTI142);
TMP42[15].name = "baseName";
TMP755[3] = &TMP42[16];
TMP42[16].kind = 1;
TMP42[16].offset = offsetof(trollingfilelogger133030, Logfiles);
TMP42[16].typ = (&NTI105);
TMP42[16].name = "logFiles";
TMP42[12].len = 4; TMP42[12].kind = 2; TMP42[12].sons = &TMP755[0];
NTI133030.node = &TMP42[12];
NTI133026.size = sizeof(tconsolelogger133026);
NTI133026.kind = 17;
NTI133026.base = (&NTI133024);
NTI133026.flags = 2;
TMP42[17].len = 0; TMP42[17].kind = 2;
NTI133026.node = &TMP42[17];
}

