/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct einvalidvalue1253 einvalidvalue1253;
typedef struct esynch1229 esynch1229;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell40090 tcell40090;
typedef struct tcellseq40106 tcellseq40106;
typedef struct tgcheap42016 tgcheap42016;
typedef struct tcellset40102 tcellset40102;
typedef struct tpagedesc40098 tpagedesc40098;
typedef struct tmemregion23010 tmemregion23010;
typedef struct tsmallchunk22238 tsmallchunk22238;
typedef struct tllchunk23004 tllchunk23004;
typedef struct tbigchunk22240 tbigchunk22240;
typedef struct tintset22215 tintset22215;
typedef struct ttrunk22211 ttrunk22211;
typedef struct tavlnode23008 tavlnode23008;
typedef struct tgcstat42014 tgcstat42014;
typedef struct tbasechunk22236 tbasechunk22236;
typedef struct tfreecell22228 tfreecell22228;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY613[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY613 data;
};
typedef N_NIMCALL_PTR(void, TY1089) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY1089 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct E_Base {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct esynch1229 {
  E_Base Sup;
};
struct einvalidvalue1253 {
  esynch1229 Sup;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell40090 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq40106 {
NI Len;
NI Cap;
tcell40090** D;
};
struct tcellset40102 {
NI Counter;
NI Max;
tpagedesc40098* Head;
tpagedesc40098** Data;
};
typedef tsmallchunk22238* TY23022[512];
typedef ttrunk22211* ttrunkbuckets22213[256];
struct tintset22215 {
ttrunkbuckets22213 Data;
};
struct tmemregion23010 {
NI Minlargeobj;
NI Maxlargeobj;
TY23022 Freesmallchunks;
tllchunk23004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk22240* Freechunkslist;
tintset22215 Chunkstarts;
tavlnode23008* Root;
tavlnode23008* Deleted;
tavlnode23008* Last;
tavlnode23008* Freeavlnodes;
};
struct tgcstat42014 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap42016 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq40106 Zct;
tcellseq40106 Decstack;
tcellset40102 Cycleroots;
tcellseq40106 Tempstack;
NI Recgclock;
tmemregion23010 Region;
tgcstat42014 Stat;
};
typedef NI tskiptable85691[256];
typedef NimStringDesc* TY87500[1];
typedef NU8 tcharset83604[32];
typedef NI TY22218[8];
struct tpagedesc40098 {
tpagedesc40098* Next;
NI Key;
TY22218 Bits;
};
struct tbasechunk22236 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk22238 {
  tbasechunk22236 Sup;
tsmallchunk22238* Next;
tsmallchunk22238* Prev;
tfreecell22228* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk23004 {
NI Size;
NI Acc;
tllchunk23004* Next;
};
struct tbigchunk22240 {
  tbasechunk22236 Sup;
tbigchunk22240* Next;
tbigchunk22240* Prev;
NI Align;
NF Data;
};
struct ttrunk22211 {
ttrunk22211* Next;
NI Key;
TY22218 Bits;
};
typedef tavlnode23008* TY23014[2];
struct tavlnode23008 {
TY23014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell22228 {
tfreecell22228* Next;
NI Zerofield;
};
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NOINLINE(void, invalidformatstring_87209)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell40090*, usrtocell_43442)(void* usr);
static N_INLINE(void, rtladdzct_45002)(tcell40090* c);
N_NOINLINE(void, addzct_43418)(tcellseq40106* s, tcell40090* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, findnormalized_87182)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_69024, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, preprocesssub_85694)(NimStringDesc* sub, NI* a);
N_NIMCALL(NI, findaux_85732)(NimStringDesc* s, NimStringDesc* sub, NI start, tskiptable85691 a);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, unsigned int* number, NI start);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
STRING_LITERAL(TMP78, "invalid format string", 21);
STRING_LITERAL(TMP97, "", 0);
STRING_LITERAL(TMP165, "invalid integer: ", 17);
extern TNimType NTI17401; /* ref EInvalidValue */
extern TNimType NTI1253; /* EInvalidValue */
extern tgcheap42016 gch_42044;
extern TNimType NTI105; /* int */
TNimType NTI85691; /* TSkipTable */

N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c) {
	NIM_CHAR result;
	result = 0;
	{
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		result = ((NIM_CHAR) (((NI) ((NI64)(((NI) (((NU8)(c)))) + 32)))));
	}
	goto LA1;
	LA3: ;
	{
		result = c;
	}
	LA1: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars) {
	NimStringDesc* result;
	NI i_84802;
	NI HEX3Atmp_84804;
	NI res_84806;
	result = 0;
	result = nimIntToStr((NI64)abs(x));
	i_84802 = 0;
	HEX3Atmp_84804 = 0;
	HEX3Atmp_84804 = (NI64)(minchars - result->Sup.len);
	res_84806 = 1;
	while (1) {
		NimStringDesc* LOC2;
		if (!(res_84806 <= HEX3Atmp_84804)) goto LA1;
		i_84802 = res_84806;
		LOC2 = 0;
		LOC2 = rawNewString(result->Sup.len + 1);
appendChar(LOC2, 48);
appendString(LOC2, result);
		result = LOC2;
		res_84806 += 1;
	} LA1: ;
	{
		NimStringDesc* LOC7;
		if (!(x < 0)) goto LA5;
		LOC7 = 0;
		LOC7 = rawNewString(result->Sup.len + 1);
appendChar(LOC7, 45);
appendString(LOC7, result);
		result = LOC7;
	}
	LA5: ;
	return result;
}

static N_INLINE(tcell40090*, usrtocell_43442)(void* usr) {
	tcell40090* result;
	result = 0;
	result = ((tcell40090*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell40090))))));
	return result;
}

static N_INLINE(void, rtladdzct_45002)(tcell40090* c) {
	addzct_43418(&gch_42044.Zct, c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell40090* c;
	c = usrtocell_43442(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_45002(c);
	}
	LA3: ;
}

N_NOINLINE(void, invalidformatstring_87209)(void) {
	einvalidvalue1253* e_87213;
	NimStringDesc* LOC1;
	e_87213 = 0;
	e_87213 = (einvalidvalue1253*) newObj((&NTI17401), sizeof(einvalidvalue1253));
	(*e_87213).Sup.Sup.Sup.m_type = (&NTI1253);
	LOC1 = 0;
	LOC1 = (*e_87213).Sup.Sup.message; (*e_87213).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP78));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	raiseException((E_Base*)e_87213, "EInvalidValue");
}

N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI j;
	result = 0;
	i = 0;
	j = 0;
	while (1) {
		NIM_CHAR aa;
		NIM_CHAR bb;
		while (1) {
			if (!((NU8)(a->data[i]) == (NU8)(95))) goto LA2;
			i += 1;
		} LA2: ;
		while (1) {
			if (!((NU8)(b->data[j]) == (NU8)(95))) goto LA3;
			j += 1;
		} LA3: ;
		aa = nsuToLowerChar(a->data[i]);
		bb = nsuToLowerChar(b->data[j]);
		result = (NI64)(((NI) (((NU8)(aa)))) - ((NI) (((NU8)(bb)))));
		{
			NIM_BOOL LOC6;
			LOC6 = 0;
			LOC6 = !((result == 0));
			if (LOC6) goto LA7;
			LOC6 = ((NU8)(aa) == (NU8)(0));
			LA7: ;
			if (!LOC6) goto LA8;
			goto LA1;
		}
		LA8: ;
		i += 1;
		j += 1;
	} LA1: ;
	return result;
}

N_NIMCALL(NI, findnormalized_87182)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0) {
	NI result;
	NI i;
	result = 0;
	i = 0;
	while (1) {
		if (!(i < (inarrayLen0-1))) goto LA1;
		{
			NI LOC4;
			LOC4 = 0;
			LOC4 = nsuCmpIgnoreStyle(x, inarray[i]);
			if (!(LOC4 == 0)) goto LA5;
			result = i;
			goto BeforeRet;
		}
		LA5: ;
		i += 2;
	} LA1: ;
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NI i;
	NI num;
	i = 0;
	num = 0;
	while (1) {
		if (!(i < formatstr->Sup.len)) goto LA1;
		{
			if (!((NU8)(formatstr->data[i]) == (NU8)(36))) goto LA4;
			switch (((NU8)(formatstr->data[(NI64)(i + 1)]))) {
			case 35:
			{
				{
					if (!((NU64)((aLen0-1)) < (NU64)(num))) goto LA9;
					invalidformatstring_87209();
				}
				LA9: ;
				(*s) = resizeString((*s), a[num]->Sup.len + 0);
appendString((*s), a[num]);
				i += 2;
				num += 1;
			}
			break;
			case 36:
			{
				(*s) = addChar((*s), 36);
				i += 2;
			}
			break;
			case 49 ... 57:
			case 45:
			{
				NI j;
				NIM_BOOL negative;
				NI idx;
				j = 0;
				i += 1;
				negative = ((NU8)(formatstr->data[i]) == (NU8)(45));
				{
					if (!negative) goto LA15;
					i += 1;
				}
				LA15: ;
				while (1) {
					if (!(((NU8)(formatstr->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr->data[i])) <= ((NU8)(57)))) goto LA17;
					j = (NI64)((NI64)((NI64)(j * 10) + ((NI) (((NU8)(formatstr->data[i]))))) - 48);
					i += 1;
				} LA17: ;
				{
					if (!!(negative)) goto LA20;
					idx = (NI64)(j - 1);
				}
				goto LA18;
				LA20: ;
				{
					idx = (NI64)(aLen0 - j);
				}
				LA18: ;
				{
					if (!((NU64)((aLen0-1)) < (NU64)(idx))) goto LA25;
					invalidformatstring_87209();
				}
				LA25: ;
				(*s) = resizeString((*s), a[idx]->Sup.len + 0);
appendString((*s), a[idx]);
			}
			break;
			case 123:
			{
				NI j;
				NI x;
				NimStringDesc* LOC29;
				j = (NI64)(i + 1);
				while (1) {
					if (!!((((NU8)(formatstr->data[j])) == ((NU8)(0)) || ((NU8)(formatstr->data[j])) == ((NU8)(125))))) goto LA28;
					j += 1;
				} LA28: ;
				LOC29 = 0;
				LOC29 = copyStrLast(formatstr, (NI64)(i + 2), (NI64)(j - 1));
				x = findnormalized_87182(LOC29, a, aLen0);
				{
					NIM_BOOL LOC32;
					LOC32 = 0;
					LOC32 = (0 <= x);
					if (!(LOC32)) goto LA33;
					LOC32 = (x < (aLen0-1));
					LA33: ;
					if (!LOC32) goto LA34;
					(*s) = resizeString((*s), a[(NI64)(x + 1)]->Sup.len + 0);
appendString((*s), a[(NI64)(x + 1)]);
				}
				goto LA30;
				LA34: ;
				{
					invalidformatstring_87209();
				}
				LA30: ;
				i = (NI64)(j + 1);
			}
			break;
			case 97 ... 122:
			case 65 ... 90:
			case 128 ... 255:
			case 95:
			{
				NI j;
				NI x;
				NimStringDesc* LOC39;
				j = (NI64)(i + 1);
				while (1) {
					if (!(((NU8)(formatstr->data[j])) >= ((NU8)(97)) && ((NU8)(formatstr->data[j])) <= ((NU8)(122)) || ((NU8)(formatstr->data[j])) >= ((NU8)(65)) && ((NU8)(formatstr->data[j])) <= ((NU8)(90)) || ((NU8)(formatstr->data[j])) >= ((NU8)(48)) && ((NU8)(formatstr->data[j])) <= ((NU8)(57)) || ((NU8)(formatstr->data[j])) >= ((NU8)(128)) && ((NU8)(formatstr->data[j])) <= ((NU8)(255)) || ((NU8)(formatstr->data[j])) == ((NU8)(95)))) goto LA38;
					j += 1;
				} LA38: ;
				LOC39 = 0;
				LOC39 = copyStrLast(formatstr, (NI64)(i + 1), (NI64)(j - 1));
				x = findnormalized_87182(LOC39, a, aLen0);
				{
					NIM_BOOL LOC42;
					LOC42 = 0;
					LOC42 = (0 <= x);
					if (!(LOC42)) goto LA43;
					LOC42 = (x < (aLen0-1));
					LA43: ;
					if (!LOC42) goto LA44;
					(*s) = resizeString((*s), a[(NI64)(x + 1)]->Sup.len + 0);
appendString((*s), a[(NI64)(x + 1)]);
				}
				goto LA40;
				LA44: ;
				{
					invalidformatstring_87209();
				}
				LA40: ;
				i = j;
			}
			break;
			default:
			{
				invalidformatstring_87209();
			}
			break;
			}
		}
		goto LA2;
		LA4: ;
		{
			(*s) = addChar((*s), formatstr->data[i]);
			i += 1;
		}
		LA2: ;
	} LA1: ;
}

N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NimStringDesc* result;
	result = 0;
	result = rawNewString((NI64)(formatstr->Sup.len + (NI)((NU64)(aLen0) << (NU64)(4))));
	nsuAddf(&result, formatstr, a, aLen0);
	return result;
}

N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c) {
	NimStringDesc* result;
	NI i_85142;
	NI HEX3Atmp_85143;
	NI res_85145;
	result = 0;
	result = mnewString(count);
	i_85142 = 0;
	HEX3Atmp_85143 = 0;
	HEX3Atmp_85143 = (NI64)(count - 1);
	res_85145 = 0;
	while (1) {
		if (!(res_85145 <= HEX3Atmp_85143)) goto LA1;
		i_85142 = res_85145;
		result->data[i_85142] = c;
		res_85145 += 1;
	} LA1: ;
	return result;
}

N_NIMCALL(void, preprocesssub_85694)(NimStringDesc* sub, NI* a) {
	NI m;
	NI i_85710;
	NI res_85722;
	NI i_85720;
	NI HEX3Atmp_85724;
	NI res_85726;
	m = sub->Sup.len;
	i_85710 = 0;
	res_85722 = 0;
	while (1) {
		if (!(res_85722 <= 255)) goto LA1;
		i_85710 = res_85722;
		a[(((NU8)(((NIM_CHAR) (((NI) (i_85710)))))))- 0] = (NI64)(m + 1);
		res_85722 += 1;
	} LA1: ;
	i_85720 = 0;
	HEX3Atmp_85724 = 0;
	HEX3Atmp_85724 = (NI64)(m - 1);
	res_85726 = 0;
	while (1) {
		if (!(res_85726 <= HEX3Atmp_85724)) goto LA2;
		i_85720 = res_85726;
		a[(((NU8)(sub->data[i_85720])))- 0] = (NI64)(m - i_85720);
		res_85726 += 1;
	} LA2: ;
}

N_NIMCALL(NI, findaux_85732)(NimStringDesc* s, NimStringDesc* sub, NI start, tskiptable85691 a) {
	NI result;
	NI m;
	NI n;
	NI j;
	result = 0;
	m = sub->Sup.len;
	n = s->Sup.len;
	j = start;
	while (1) {
		if (!(j <= (NI64)(n - m))) goto LA1;
		{
			NI k_85752;
			NI HEX3Atmp_85769;
			NI res_85771;
			k_85752 = 0;
			HEX3Atmp_85769 = 0;
			HEX3Atmp_85769 = (NI64)(m - 1);
			res_85771 = 0;
			while (1) {
				if (!(res_85771 <= HEX3Atmp_85769)) goto LA3;
				k_85752 = res_85771;
				{
					if (!!(((NU8)(sub->data[k_85752]) == (NU8)(s->data[(NI64)(k_85752 + j)])))) goto LA6;
					goto LA2;
				}
				LA6: ;
				res_85771 += 1;
			} LA3: ;
			result = j;
			goto BeforeRet;
		} LA2: ;
		j += a[(((NU8)(s->data[(NI64)(j + m)])))- 0];
	} LA1: ;
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by) {
	NimStringDesc* result;
	tskiptable85691 a;
	NI i;
	NimStringDesc* LOC7;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP97));
	preprocesssub_85694(sub, a);
	i = 0;
	while (1) {
		NI j;
		NimStringDesc* LOC6;
		j = findaux_85732(s, sub, i, a);
		{
			if (!(j < 0)) goto LA4;
			goto LA1;
		}
		LA4: ;
		LOC6 = 0;
		LOC6 = copyStrLast(s, i, (NI64)(j - 1));
		result = resizeString(result, LOC6->Sup.len + 0);
appendString(result, LOC6);
		result = resizeString(result, by->Sup.len + 0);
appendString(result, by);
		i = (NI64)(j + sub->Sup.len);
	} LA1: ;
	LOC7 = 0;
	LOC7 = copyStr(s, i);
	result = resizeString(result, LOC7->Sup.len + 0);
appendString(result, LOC7);
	return result;
}

N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI m;
	result = 0;
	i = 0;
	m = ((a->Sup.len <= b->Sup.len) ? a->Sup.len : b->Sup.len);
	while (1) {
		NIM_CHAR LOC2;
		NIM_CHAR LOC3;
		if (!(i < m)) goto LA1;
		LOC2 = 0;
		LOC2 = nsuToLowerChar(a->data[i]);
		LOC3 = 0;
		LOC3 = nsuToLowerChar(b->data[i]);
		result = (NI64)(((NI) (((NU8)(LOC2)))) - ((NI) (((NU8)(LOC3)))));
		{
			if (!!((result == 0))) goto LA6;
			goto BeforeRet;
		}
		LA6: ;
		i += 1;
	} LA1: ;
	result = (NI64)(a->Sup.len - b->Sup.len);
	BeforeRet: ;
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell40090* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_43442(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell40090* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_43442((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_45002(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s) {
	NI result;
	NI l;
	result = 0;
	l = npuParseInt(s, &result, 0);
	{
		NIM_BOOL LOC3;
		einvalidvalue1253* e_84819;
		NimStringDesc* LOC7;
		LOC3 = 0;
		LOC3 = !((l == s->Sup.len));
		if (LOC3) goto LA4;
		LOC3 = (l == 0);
		LA4: ;
		if (!LOC3) goto LA5;
		e_84819 = 0;
		e_84819 = (einvalidvalue1253*) newObj((&NTI17401), sizeof(einvalidvalue1253));
		(*e_84819).Sup.Sup.Sup.m_type = (&NTI1253);
		LOC7 = 0;
		LOC7 = rawNewString(s->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &TMP165));
appendString(LOC7, s);
		asgnRefNoCycle((void**) &(*e_84819).Sup.Sup.message, LOC7);
		raiseException((E_Base*)e_84819, "EInvalidValue");
	}
	LA5: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a) {
	NimStringDesc* result;
	TY87500 LOC1;
	result = 0;
	result = rawNewString((NI64)(formatstr->Sup.len + a->Sup.len));
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = copyString(a);
	nsuAddf(&result, formatstr, LOC1, 1);
	return result;
}

N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix) {
	NIM_BOOL result;
	NI i;
	result = 0;
	i = 0;
	while (1) {
		{
			if (!((NU8)(prefix->data[i]) == (NU8)(0))) goto LA4;
			result = NIM_TRUE;
			goto BeforeRet;
		}
		LA4: ;
		{
			if (!!(((NU8)(s->data[i]) == (NU8)(prefix->data[i])))) goto LA8;
			result = NIM_FALSE;
			goto BeforeRet;
		}
		LA8: ;
		i += 1;
	}
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start) {
	NI result;
	NI i_85804;
	NI HEX3Atmp_85805;
	NI res_85807;
	result = 0;
	i_85804 = 0;
	HEX3Atmp_85805 = 0;
	HEX3Atmp_85805 = (NI64)(s->Sup.len - 1);
	res_85807 = start;
	while (1) {
		if (!(res_85807 <= HEX3Atmp_85805)) goto LA1;
		i_85804 = res_85807;
		{
			if (!((NU8)(sub) == (NU8)(s->data[i_85804]))) goto LA4;
			result = i_85804;
			goto BeforeRet;
		}
		LA4: ;
		res_85807 += 1;
	} LA1: ;
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, allcharsinset_85507)(NimStringDesc* s, tcharset83604 theset) {
	NIM_BOOL result;
	NIM_CHAR c_85512;
	NI i_85526;
	result = 0;
	c_85512 = 0;
	i_85526 = 0;
	while (1) {
		if (!(i_85526 < s->Sup.len)) goto LA1;
		c_85512 = s->data[i_85526];
		{
			if (!!(((theset[((NU8)(c_85512))/8] &(1<<(((NU8)(c_85512))%8)))!=0))) goto LA4;
			result = NIM_FALSE;
			goto BeforeRet;
		}
		LA4: ;
		i_85526 += 1;
	} LA1: ;
	result = NIM_TRUE;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, nsuContinuesWith)(NimStringDesc* s, NimStringDesc* substr, NI start) {
	NIM_BOOL result;
	NI i;
	result = 0;
	i = 0;
	while (1) {
		{
			if (!((NU8)(substr->data[i]) == (NU8)(0))) goto LA4;
			result = NIM_TRUE;
			goto BeforeRet;
		}
		LA4: ;
		{
			if (!!(((NU8)(s->data[(NI64)(i + start)]) == (NU8)(substr->data[i])))) goto LA8;
			result = NIM_FALSE;
			goto BeforeRet;
		}
		LA8: ;
		i += 1;
	}
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing) {
	NimStringDesc* result;
	NI first;
	NI last;
	result = 0;
	first = 0;
	last = (NI64)(s->Sup.len - 1);
	{
		if (!leading) goto LA3;
		while (1) {
			if (!(((NU8)(s->data[first])) == ((NU8)(32)) || ((NU8)(s->data[first])) == ((NU8)(9)) || ((NU8)(s->data[first])) == ((NU8)(11)) || ((NU8)(s->data[first])) == ((NU8)(13)) || ((NU8)(s->data[first])) == ((NU8)(10)) || ((NU8)(s->data[first])) == ((NU8)(12)))) goto LA5;
			first += 1;
		} LA5: ;
	}
	LA3: ;
	{
		if (!trailing) goto LA8;
		while (1) {
			NIM_BOOL LOC11;
			LOC11 = 0;
			LOC11 = (0 <= last);
			if (!(LOC11)) goto LA12;
			LOC11 = (((NU8)(s->data[last])) == ((NU8)(32)) || ((NU8)(s->data[last])) == ((NU8)(9)) || ((NU8)(s->data[last])) == ((NU8)(11)) || ((NU8)(s->data[last])) == ((NU8)(13)) || ((NU8)(s->data[last])) == ((NU8)(10)) || ((NU8)(s->data[last])) == ((NU8)(12)));
			LA12: ;
			if (!LOC11) goto LA10;
			last -= 1;
		} LA10: ;
	}
	LA8: ;
	result = copyStrLast(s, first, last);
	return result;
}
N_NOINLINE(void, purestrutilsInit)(void) {
}

N_NOINLINE(void, purestrutilsDatInit)(void) {
NTI85691.size = sizeof(tskiptable85691);
NTI85691.kind = 16;
NTI85691.base = (&NTI105);
NTI85691.flags = 3;
}

