/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcfgparser126612 tcfgparser126612;
typedef struct tbaselexer124008 tbaselexer124008;
typedef struct TNimObject TNimObject;
typedef struct tstream123033 tstream123033;
typedef struct ttoken126610 ttoken126610;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcfgevent126606 tcfgevent126606;
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TNimObject {
TNimType* m_type;
};
struct tbaselexer124008 {
  TNimObject Sup;
NI Bufpos;
NCSTRING Buf;
NI Buflen;
tstream123033* Input;
NI Linenumber;
NI Sentinel;
NI Linestart;
NIM_BOOL Fileopened;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct ttoken126610 {
NU8 Kind;
NimStringDesc* Literal;
};
struct tcfgparser126612 {
  tbaselexer124008 Sup;
ttoken126610 Tok;
NimStringDesc* Filename;
};
struct tcfgevent126606 {
  TNimObject Sup;
NU8 Kind;
union {
struct {NimStringDesc* Section;
} S2;
struct {NimStringDesc* Key;
NimStringDesc* Value;
} S3;
struct {NimStringDesc* Msg;
} S4;
} kindU;
};
typedef NimStringDesc* TY133122[4];
typedef N_NIMCALL_PTR(void, TY123034) (tstream123033* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY123038) (tstream123033* s);
typedef N_NIMCALL_PTR(void, TY123042) (tstream123033* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY123047) (tstream123033* s);
typedef N_NIMCALL_PTR(NI, TY123051) (tstream123033* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY123057) (tstream123033* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY123063) (tstream123033* s);
struct tstream123033 {
  TNimObject Sup;
TY123034 Closeimpl;
TY123038 Atendimpl;
TY123042 Setpositionimpl;
TY123047 Getpositionimpl;
TY123051 Readdataimpl;
TY123057 Writedataimpl;
TY123063 Flushimpl;
};
N_NIMCALL(void, open_124018)(tbaselexer124008* l, tstream123033* input, NI buflen);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, rawgettok_126640)(tcfgparser126612* c, ttoken126610* tok);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(void, skip_127085)(tcfgparser126612* c);
N_NIMCALL(NI, handlecrlf_126969)(tcfgparser126612* c, NI pos);
N_NIMCALL(NI, handlecr_124041)(tbaselexer124008* l, NI pos);
N_NIMCALL(NI, handlelf_124047)(tbaselexer124008* l, NI pos);
N_NIMCALL(void, getstring_126979)(tcfgparser126612* c, ttoken126610* tok, NIM_BOOL rawmode);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(void, getescapedchar_126825)(tcfgparser126612* c, ttoken126610* tok);
N_NIMCALL(void, handlehexchar_126693)(tcfgparser126612* c, unsigned int* xi);
N_NIMCALL(void, handledecchars_126780)(tcfgparser126612* c, unsigned int* xi);
N_NIMCALL(void, getsymbol_127054)(tcfgparser126612* c, ttoken126610* tok);
N_NIMCALL(void, getkeyvalpair_127288)(tcfgparser126612* c, NU8 kind, tcfgevent126606* Result);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(NimStringDesc*, npcerrorStr)(tcfgparser126612* c, NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(NI, npcgetLine)(tcfgparser126612* c);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NI, npcgetColumn)(tcfgparser126612* c);
N_NIMCALL(NI, getcolnumber_124036)(tbaselexer124008* l, NI pos);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, close_124026)(tbaselexer124008* l);
STRING_LITERAL(TMP130, "", 0);
STRING_LITERAL(TMP131, "=", 1);
STRING_LITERAL(TMP132, "--", 2);
STRING_LITERAL(TMP133, ":", 1);
STRING_LITERAL(TMP134, "\012", 1);
STRING_LITERAL(TMP135, "]", 1);
STRING_LITERAL(TMP136, "[EOF]", 5);
TNimNode* NimDT_tcfgevent_kind[6];
STRING_LITERAL(TMP142, "$1($2, $3) Error: $4", 20);
STRING_LITERAL(TMP143, "symbol expected, but found: ", 28);
STRING_LITERAL(TMP144, "\']\' expected, but found: ", 25);
STRING_LITERAL(TMP145, "invalid token: ", 15);
extern TNimType NTI124008; /* TBaseLexer */
TNimType NTI126612; /* TCfgParser */
TNimType NTI126610; /* TToken */
TNimType NTI126608; /* TTokKind */
extern TNimType NTI142; /* string */
extern TNimType NTI1009; /* TObject */
TNimType NTI126606; /* TCfgEvent */
TNimType NTI126604; /* TCfgEventKind */

N_NIMCALL(NI, handlecrlf_126969)(tcfgparser126612* c, NI pos) {
	NI result;
	result = 0;
	switch (((NU8)((*c).Sup.Buf[pos]))) {
	case 13:
	{
		result = handlecr_124041(&c->Sup, pos);
	}	break;
	case 10:
	{
		result = handlelf_124047(&c->Sup, pos);
	}	break;
	default:
	{
		result = pos;
	}	break;
	}
	return result;
}
N_NIMCALL(void, skip_127085)(tcfgparser126612* c) {
	NI pos;
	NCSTRING buf;
	pos = (*c).Sup.Bufpos;
	buf = (*c).Sup.Buf;
	while (1) {
		switch (((NU8)(buf[pos]))) {
		case 32:
		case 9:
		{
			pos += 1;
		}		break;
		case 35:
		case 59:
		{
			while (1) {
				if (!!((((NU8)(buf[pos])) == ((NU8)(13)) || ((NU8)(buf[pos])) == ((NU8)(10)) || ((NU8)(buf[pos])) == ((NU8)(0))))) goto LA4;
				pos += 1;
			} LA4: ;
		}		break;
		case 13:
		case 10:
		{
			pos = handlecrlf_126969(c, pos);
			buf = (*c).Sup.Buf;
		}		break;
		default:
		{
			goto LA1;
		}		break;
		}
	} LA1: ;
	(*c).Sup.Bufpos = pos;
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));	(*dest).Sup.len += (*src).Sup.len;
}
N_NIMCALL(void, handlehexchar_126693)(tcfgparser126612* c, unsigned int* xi) {
	switch (((NU8)((*c).Sup.Buf[(*c).Sup.Bufpos]))) {
	case 48 ... 57:
	{
		(*xi) = (NI)((NI)((NU64)((*xi)) << (NU64)(4)) | ((NI) ((NI64)(((NI) (((NU8)((*c).Sup.Buf[(*c).Sup.Bufpos])))) - 48))));
		(*c).Sup.Bufpos += 1;
	}	break;
	case 97 ... 102:
	{
		(*xi) = (NI)((NI)((NU64)((*xi)) << (NU64)(4)) | ((NI) ((NI64)(((NI) ((NI64)(((NI) (((NU8)((*c).Sup.Buf[(*c).Sup.Bufpos])))) - 97))) + 10))));
		(*c).Sup.Bufpos += 1;
	}	break;
	case 65 ... 70:
	{
		(*xi) = (NI)((NI)((NU64)((*xi)) << (NU64)(4)) | ((NI) ((NI64)(((NI) ((NI64)(((NI) (((NU8)((*c).Sup.Buf[(*c).Sup.Bufpos])))) - 65))) + 10))));
		(*c).Sup.Bufpos += 1;
	}	break;
	default:
	{
	}	break;
	}
}
N_NIMCALL(void, handledecchars_126780)(tcfgparser126612* c, unsigned int* xi) {
	while (1) {
		if (!(((NU8)((*c).Sup.Buf[(*c).Sup.Bufpos])) >= ((NU8)(48)) && ((NU8)((*c).Sup.Buf[(*c).Sup.Bufpos])) <= ((NU8)(57)))) goto LA1;
		(*xi) = (NI64)((NI64)((*xi) * 10) + ((NI) ((NI64)(((NI) (((NU8)((*c).Sup.Buf[(*c).Sup.Bufpos])))) - 48))));
		(*c).Sup.Bufpos += 1;
	} LA1: ;
}
N_NIMCALL(void, getescapedchar_126825)(tcfgparser126612* c, ttoken126610* tok) {
	(*c).Sup.Bufpos += 1;
	switch (((NU8)((*c).Sup.Buf[(*c).Sup.Bufpos]))) {
	case 110:
	case 78:
	{
		(*tok).Literal = resizeString((*tok).Literal, 1);
appendString((*tok).Literal, ((NimStringDesc*) &TMP134));
		(*c).Sup.Bufpos += 1;
	}	break;
	case 114:
	case 82:
	case 99:
	case 67:
	{
		(*tok).Literal = addChar((*tok).Literal, 13);
		(*c).Sup.Bufpos += 1;
	}	break;
	case 108:
	case 76:
	{
		(*tok).Literal = addChar((*tok).Literal, 10);
		(*c).Sup.Bufpos += 1;
	}	break;
	case 102:
	case 70:
	{
		(*tok).Literal = addChar((*tok).Literal, 12);
		(*c).Sup.Bufpos += 1;
	}	break;
	case 101:
	case 69:
	{
		(*tok).Literal = addChar((*tok).Literal, 27);
		(*c).Sup.Bufpos += 1;
	}	break;
	case 97:
	case 65:
	{
		(*tok).Literal = addChar((*tok).Literal, 7);
		(*c).Sup.Bufpos += 1;
	}	break;
	case 98:
	case 66:
	{
		(*tok).Literal = addChar((*tok).Literal, 8);
		(*c).Sup.Bufpos += 1;
	}	break;
	case 118:
	case 86:
	{
		(*tok).Literal = addChar((*tok).Literal, 11);
		(*c).Sup.Bufpos += 1;
	}	break;
	case 116:
	case 84:
	{
		(*tok).Literal = addChar((*tok).Literal, 9);
		(*c).Sup.Bufpos += 1;
	}	break;
	case 39:
	case 34:
	{
		(*tok).Literal = addChar((*tok).Literal, (*c).Sup.Buf[(*c).Sup.Bufpos]);
		(*c).Sup.Bufpos += 1;
	}	break;
	case 92:
	{
		(*tok).Literal = addChar((*tok).Literal, 92);
		(*c).Sup.Bufpos += 1;
	}	break;
	case 120:
	case 88:
	{
		NI xi;
		(*c).Sup.Bufpos += 1;
		xi = 0;
		handlehexchar_126693(c, &xi);		handlehexchar_126693(c, &xi);		(*tok).Literal = addChar((*tok).Literal, ((NIM_CHAR) (((NI) (xi)))));
	}	break;
	case 48 ... 57:
	{
		NI xi;
		xi = 0;
		handledecchars_126780(c, &xi);		{
			if (!(xi <= 255)) goto LA16;
			(*tok).Literal = addChar((*tok).Literal, ((NIM_CHAR) (((NI) (xi)))));
		}		goto LA14;
		LA16: ;
		{
			(*tok).Kind = ((NU8) 0);
		}		LA14: ;
	}	break;
	default:
	{
		(*tok).Kind = ((NU8) 0);
	}	break;
	}
}
N_NIMCALL(void, getstring_126979)(tcfgparser126612* c, ttoken126610* tok, NIM_BOOL rawmode) {
	NI pos;
	NCSTRING buf;
	pos = (NI64)((*c).Sup.Bufpos + 1);
	buf = (*c).Sup.Buf;
	(*tok).Kind = ((NU8) 2);
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((NU8)(buf[pos]) == (NU8)(34));
		if (!(LOC3)) goto LA4;
		LOC3 = ((NU8)(buf[(NI64)(pos + 1)]) == (NU8)(34));
		LA4: ;
		if (!LOC3) goto LA5;
		pos += 2;
		pos = handlecrlf_126969(c, pos);
		buf = (*c).Sup.Buf;
		while (1) {
			switch (((NU8)(buf[pos]))) {
			case 34:
			{
				{
					NIM_BOOL LOC11;
					LOC11 = 0;
					LOC11 = ((NU8)(buf[(NI64)(pos + 1)]) == (NU8)(34));
					if (!(LOC11)) goto LA12;
					LOC11 = ((NU8)(buf[(NI64)(pos + 2)]) == (NU8)(34));
					LA12: ;
					if (!LOC11) goto LA13;
					goto LA7;
				}				LA13: ;
				(*tok).Literal = addChar((*tok).Literal, 34);
				pos += 1;
			}			break;
			case 13:
			case 10:
			{
				pos = handlecrlf_126969(c, pos);
				buf = (*c).Sup.Buf;
				(*tok).Literal = resizeString((*tok).Literal, 1);
appendString((*tok).Literal, ((NimStringDesc*) &TMP134));
			}			break;
			case 0:
			{
				(*tok).Kind = ((NU8) 0);
				goto LA7;
			}			break;
			default:
			{
				(*tok).Literal = addChar((*tok).Literal, buf[pos]);
				pos += 1;
			}			break;
			}
		} LA7: ;
		(*c).Sup.Bufpos = (NI64)(pos + 3);
	}	goto LA1;
	LA5: ;
	{
		while (1) {
			NIM_CHAR ch;
			ch = buf[pos];
			{
				if (!((NU8)(ch) == (NU8)(34))) goto LA22;
				pos += 1;
				goto LA19;
			}			LA22: ;
			{
				if (!(((NU8)(ch)) == ((NU8)(13)) || ((NU8)(ch)) == ((NU8)(10)) || ((NU8)(ch)) == ((NU8)(0)))) goto LA26;
				(*tok).Kind = ((NU8) 0);
				goto LA19;
			}			LA26: ;
			{
				NIM_BOOL LOC30;
				LOC30 = 0;
				LOC30 = ((NU8)(ch) == (NU8)(92));
				if (!(LOC30)) goto LA31;
				LOC30 = !(rawmode);
				LA31: ;
				if (!LOC30) goto LA32;
				(*c).Sup.Bufpos = pos;
				getescapedchar_126825(c, tok);				pos = (*c).Sup.Bufpos;
			}			goto LA28;
			LA32: ;
			{
				(*tok).Literal = addChar((*tok).Literal, ch);
				pos += 1;
			}			LA28: ;
		} LA19: ;
		(*c).Sup.Bufpos = pos;
	}	LA1: ;
}
N_NIMCALL(void, getsymbol_127054)(tcfgparser126612* c, ttoken126610* tok) {
	NI pos;
	NCSTRING buf;
	pos = (*c).Sup.Bufpos;
	buf = (*c).Sup.Buf;
	while (1) {
		(*tok).Literal = addChar((*tok).Literal, buf[pos]);
		pos += 1;
		{
			if (!!((((NU8)(buf[pos])) >= ((NU8)(97)) && ((NU8)(buf[pos])) <= ((NU8)(122)) || ((NU8)(buf[pos])) >= ((NU8)(65)) && ((NU8)(buf[pos])) <= ((NU8)(90)) || ((NU8)(buf[pos])) >= ((NU8)(48)) && ((NU8)(buf[pos])) <= ((NU8)(57)) || ((NU8)(buf[pos])) == ((NU8)(95)) || ((NU8)(buf[pos])) >= ((NU8)(128)) && ((NU8)(buf[pos])) <= ((NU8)(255)) || ((NU8)(buf[pos])) == ((NU8)(46)) || ((NU8)(buf[pos])) == ((NU8)(47)) || ((NU8)(buf[pos])) == ((NU8)(92))))) goto LA4;
			goto LA1;
		}		LA4: ;
	} LA1: ;
	(*c).Sup.Bufpos = pos;
	(*tok).Kind = ((NU8) 2);
}
N_NIMCALL(void, rawgettok_126640)(tcfgparser126612* c, ttoken126610* tok) {
	(*tok).Kind = ((NU8) 0);
	(*tok).Literal = setLengthStr((*tok).Literal, 0);
	skip_127085(c);	switch (((NU8)((*c).Sup.Buf[(*c).Sup.Bufpos]))) {
	case 61:
	{
		(*tok).Kind = ((NU8) 3);
		(*c).Sup.Bufpos += 1;
		unsureAsgnRef((void**) &(*tok).Literal, copyString(((NimStringDesc*) &TMP131)));
	}	break;
	case 45:
	{
		(*c).Sup.Bufpos += 1;
		{
			if (!((NU8)((*c).Sup.Buf[(*c).Sup.Bufpos]) == (NU8)(45))) goto LA5;
			(*c).Sup.Bufpos += 1;
		}		LA5: ;
		(*tok).Kind = ((NU8) 7);
		unsureAsgnRef((void**) &(*tok).Literal, copyString(((NimStringDesc*) &TMP132)));
	}	break;
	case 58:
	{
		(*tok).Kind = ((NU8) 4);
		(*c).Sup.Bufpos += 1;
		unsureAsgnRef((void**) &(*tok).Literal, copyString(((NimStringDesc*) &TMP133)));
	}	break;
	case 114:
	case 82:
	{
		{
			if (!((NU8)((*c).Sup.Buf[(NI64)((*c).Sup.Bufpos + 1)]) == (NU8)(34))) goto LA11;
			(*c).Sup.Bufpos += 1;
			getstring_126979(c, tok, NIM_TRUE);		}		goto LA9;
		LA11: ;
		{
			getsymbol_127054(c, tok);		}		LA9: ;
	}	break;
	case 91:
	{
		(*tok).Kind = ((NU8) 5);
		(*c).Sup.Bufpos += 1;
		unsureAsgnRef((void**) &(*tok).Literal, copyString(((NimStringDesc*) &TMP135)));
	}	break;
	case 93:
	{
		(*tok).Kind = ((NU8) 6);
		(*c).Sup.Bufpos += 1;
		unsureAsgnRef((void**) &(*tok).Literal, copyString(((NimStringDesc*) &TMP135)));
	}	break;
	case 34:
	{
		getstring_126979(c, tok, NIM_FALSE);	}	break;
	case 0:
	{
		(*tok).Kind = ((NU8) 1);
		unsureAsgnRef((void**) &(*tok).Literal, copyString(((NimStringDesc*) &TMP136)));
	}	break;
	default:
	{
		getsymbol_127054(c, tok);	}	break;
	}
}
N_NIMCALL(void, npcopen)(tcfgparser126612* c, tstream123033* input, NimStringDesc* filename, NI lineoffset) {
	open_124018(&c->Sup, input, 8192);	unsureAsgnRef((void**) &(*c).Filename, copyString(filename));
	(*c).Tok.Kind = ((NU8) 0);
	unsureAsgnRef((void**) &(*c).Tok.Literal, copyString(((NimStringDesc*) &TMP130)));
	(*c).Sup.Linenumber += lineoffset;
	rawgettok_126640(c, &(*c).Tok);}
N_NIMCALL(NI, npcgetLine)(tcfgparser126612* c) {
	NI result;
	result = 0;
	result = (*c).Sup.Linenumber;
	return result;
}
N_NIMCALL(NI, npcgetColumn)(tcfgparser126612* c) {
	NI result;
	result = 0;
	result = getcolnumber_124036(&(*c).Sup, (*c).Sup.Bufpos);
	return result;
}
N_NIMCALL(NimStringDesc*, npcerrorStr)(tcfgparser126612* c, NimStringDesc* msg) {
	NimStringDesc* result;
	TY133122 LOC1;
	NI LOC2;
	NI LOC3;
	result = 0;
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = copyString((*c).Filename);
	LOC2 = 0;
	LOC2 = npcgetLine(c);
	LOC1[1] = nimIntToStr(LOC2);
	LOC3 = 0;
	LOC3 = npcgetColumn(c);
	LOC1[2] = nimIntToStr(LOC3);
	LOC1[3] = copyString(msg);
	result = nsuFormatOpenArray(((NimStringDesc*) &TMP142), LOC1, 4);
	return result;
}
N_NIMCALL(void, getkeyvalpair_127288)(tcfgparser126612* c, NU8 kind, tcfgevent126606* Result) {
	{
		if (!((*c).Tok.Kind == ((NU8) 2))) goto LA3;
		(*Result).Kind = kind;
		unsureAsgnRef((void**) &(*Result).kindU.S3.Key, copyString((*c).Tok.Literal));
		unsureAsgnRef((void**) &(*Result).kindU.S3.Value, copyString(((NimStringDesc*) &TMP130)));
		rawgettok_126640(c, &(*c).Tok);		{
			if (!((24 &(1<<(((*c).Tok.Kind)&7)))!=0)) goto LA7;
			rawgettok_126640(c, &(*c).Tok);			{
				if (!((*c).Tok.Kind == ((NU8) 2))) goto LA11;
				unsureAsgnRef((void**) &(*Result).kindU.S3.Value, copyString((*c).Tok.Literal));
			}			goto LA9;
			LA11: ;
			{
				NimStringDesc* LOC14;
				genericReset((void*)Result, (&NTI126606));
				(*Result).Kind = ((NU8) 4);
				LOC14 = 0;
				LOC14 = rawNewString((*c).Tok.Literal->Sup.len + 28);
appendString(LOC14, ((NimStringDesc*) &TMP143));
appendString(LOC14, (*c).Tok.Literal);
				unsureAsgnRef((void**) &(*Result).kindU.S4.Msg, npcerrorStr(&(*c), LOC14));
			}			LA9: ;
			rawgettok_126640(c, &(*c).Tok);		}		LA7: ;
	}	goto LA1;
	LA3: ;
	{
		NimStringDesc* LOC16;
		(*Result).Kind = ((NU8) 4);
		LOC16 = 0;
		LOC16 = rawNewString((*c).Tok.Literal->Sup.len + 28);
appendString(LOC16, ((NimStringDesc*) &TMP143));
appendString(LOC16, (*c).Tok.Literal);
		unsureAsgnRef((void**) &(*Result).kindU.S4.Msg, npcerrorStr(&(*c), LOC16));
		rawgettok_126640(c, &(*c).Tok);	}	LA1: ;
}
N_NIMCALL(void, npcnext)(tcfgparser126612* c, tcfgevent126606* Result) {
	switch ((*c).Tok.Kind) {
	case ((NU8) 1):
	{
		(*Result).Kind = ((NU8) 0);
	}	break;
	case ((NU8) 7):
	{
		rawgettok_126640(c, &(*c).Tok);		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI126606));
		(*Result).Sup.m_type = (&NTI126606);
		getkeyvalpair_127288(c, ((NU8) 3), Result);	}	break;
	case ((NU8) 2):
	{
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI126606));
		(*Result).Sup.m_type = (&NTI126606);
		getkeyvalpair_127288(c, ((NU8) 2), Result);	}	break;
	case ((NU8) 5):
	{
		rawgettok_126640(c, &(*c).Tok);		{
			if (!((*c).Tok.Kind == ((NU8) 2))) goto LA7;
			(*Result).Kind = ((NU8) 1);
			unsureAsgnRef((void**) &(*Result).kindU.S2.Section, copyString((*c).Tok.Literal));
		}		goto LA5;
		LA7: ;
		{
			NimStringDesc* LOC10;
			(*Result).Kind = ((NU8) 4);
			LOC10 = 0;
			LOC10 = rawNewString((*c).Tok.Literal->Sup.len + 28);
appendString(LOC10, ((NimStringDesc*) &TMP143));
appendString(LOC10, (*c).Tok.Literal);
			unsureAsgnRef((void**) &(*Result).kindU.S4.Msg, npcerrorStr(&(*c), LOC10));
		}		LA5: ;
		rawgettok_126640(c, &(*c).Tok);		{
			if (!((*c).Tok.Kind == ((NU8) 6))) goto LA13;
			rawgettok_126640(c, &(*c).Tok);		}		goto LA11;
		LA13: ;
		{
			NimStringDesc* LOC16;
			(*Result).Kind = ((NU8) 4);
			LOC16 = 0;
			LOC16 = rawNewString((*c).Tok.Literal->Sup.len + 25);
appendString(LOC16, ((NimStringDesc*) &TMP144));
appendString(LOC16, (*c).Tok.Literal);
			unsureAsgnRef((void**) &(*Result).kindU.S4.Msg, npcerrorStr(&(*c), LOC16));
		}		LA11: ;
	}	break;
	case ((NU8) 0):
	case ((NU8) 3):
	case ((NU8) 4):
	case ((NU8) 6):
	{
		NimStringDesc* LOC18;
		(*Result).Kind = ((NU8) 4);
		LOC18 = 0;
		LOC18 = rawNewString((*c).Tok.Literal->Sup.len + 15);
appendString(LOC18, ((NimStringDesc*) &TMP145));
appendString(LOC18, (*c).Tok.Literal);
		unsureAsgnRef((void**) &(*Result).kindU.S4.Msg, npcerrorStr(&(*c), LOC18));
		rawgettok_126640(c, &(*c).Tok);	}	break;
	}
}
N_NIMCALL(void, npcclose)(tcfgparser126612* c) {
	close_124026(&c->Sup);}N_NOINLINE(void, pureparsecfgInit)(void) {
}

N_NOINLINE(void, pureparsecfgDatInit)(void) {
static TNimNode* TMP125[2];
static TNimNode* TMP126[2];
static TNimNode* TMP127[8];
NI TMP129;
static char* NIM_CONST TMP128[8] = {
"tkInvalid", 
"tkEof", 
"tkSymbol", 
"tkEquals", 
"tkColon", 
"tkBracketLe", 
"tkBracketRi", 
"tkDashDash"};
static TNimNode* TMP138[5];
NI TMP140;
static char* NIM_CONST TMP139[5] = {
"cfgEof", 
"cfgSectionStart", 
"cfgKeyValuePair", 
"cfgOption", 
"cfgError"};
static TNimNode* TMP141[2];
static TNimNode TMP30[28];
NTI126612.size = sizeof(tcfgparser126612);
NTI126612.kind = 17;
NTI126612.base = (&NTI124008);
NTI126612.flags = 2;
TMP125[0] = &TMP30[1];
NTI126610.size = sizeof(ttoken126610);
NTI126610.kind = 18;
NTI126610.base = 0;
NTI126610.flags = 2;
TMP126[0] = &TMP30[3];
NTI126608.size = sizeof(NU8);
NTI126608.kind = 14;
NTI126608.base = 0;
NTI126608.flags = 3;
for (TMP129 = 0; TMP129 < 8; TMP129++) {
TMP30[TMP129+4].kind = 1;
TMP30[TMP129+4].offset = TMP129;
TMP30[TMP129+4].name = TMP128[TMP129];
TMP127[TMP129] = &TMP30[TMP129+4];
}
TMP30[12].len = 8; TMP30[12].kind = 2; TMP30[12].sons = &TMP127[0];
NTI126608.node = &TMP30[12];
TMP30[3].kind = 1;
TMP30[3].offset = offsetof(ttoken126610, Kind);
TMP30[3].typ = (&NTI126608);
TMP30[3].name = "kind";
TMP126[1] = &TMP30[13];
TMP30[13].kind = 1;
TMP30[13].offset = offsetof(ttoken126610, Literal);
TMP30[13].typ = (&NTI142);
TMP30[13].name = "literal";
TMP30[2].len = 2; TMP30[2].kind = 2; TMP30[2].sons = &TMP126[0];
NTI126610.node = &TMP30[2];
TMP30[1].kind = 1;
TMP30[1].offset = offsetof(tcfgparser126612, Tok);
TMP30[1].typ = (&NTI126610);
TMP30[1].name = "tok";
TMP125[1] = &TMP30[14];
TMP30[14].kind = 1;
TMP30[14].offset = offsetof(tcfgparser126612, Filename);
TMP30[14].typ = (&NTI142);
TMP30[14].name = "filename";
TMP30[0].len = 2; TMP30[0].kind = 2; TMP30[0].sons = &TMP125[0];
NTI126612.node = &TMP30[0];
NTI126606.size = sizeof(tcfgevent126606);
NTI126606.kind = 17;
NTI126606.base = (&NTI1009);
NTI126606.flags = 2;
NTI126604.size = sizeof(NU8);
NTI126604.kind = 14;
NTI126604.base = 0;
NTI126604.flags = 3;
for (TMP140 = 0; TMP140 < 5; TMP140++) {
TMP30[TMP140+16].kind = 1;
TMP30[TMP140+16].offset = TMP140;
TMP30[TMP140+16].name = TMP139[TMP140];
TMP138[TMP140] = &TMP30[TMP140+16];
}
TMP30[21].len = 5; TMP30[21].kind = 2; TMP30[21].sons = &TMP138[0];
NTI126604.node = &TMP30[21];
TMP30[15].kind = 3;
TMP30[15].offset = offsetof(tcfgevent126606, Kind);
TMP30[15].typ = (&NTI126604);
TMP30[15].name = "kind";
TMP30[15].sons = &NimDT_tcfgevent_kind[0];
TMP30[15].len = 5;
TMP30[22].len = 0; TMP30[22].kind = 2;
NimDT_tcfgevent_kind[0] = &TMP30[22];
TMP30[23].kind = 1;
TMP30[23].offset = offsetof(tcfgevent126606, kindU.S2.Section);
TMP30[23].typ = (&NTI142);
TMP30[23].name = "section";
NimDT_tcfgevent_kind[1] = &TMP30[23];
TMP141[0] = &TMP30[25];
TMP30[25].kind = 1;
TMP30[25].offset = offsetof(tcfgevent126606, kindU.S3.Key);
TMP30[25].typ = (&NTI142);
TMP30[25].name = "key";
TMP141[1] = &TMP30[26];
TMP30[26].kind = 1;
TMP30[26].offset = offsetof(tcfgevent126606, kindU.S3.Value);
TMP30[26].typ = (&NTI142);
TMP30[26].name = "value";
TMP30[24].len = 2; TMP30[24].kind = 2; TMP30[24].sons = &TMP141[0];
NimDT_tcfgevent_kind[2] = &TMP30[24];
NimDT_tcfgevent_kind[3] = &TMP30[24];
TMP30[27].kind = 1;
TMP30[27].offset = offsetof(tcfgevent126606, kindU.S4.Msg);
TMP30[27].typ = (&NTI142);
TMP30[27].name = "msg";
NimDT_tcfgevent_kind[4] = &TMP30[27];
NTI126606.node = &TMP30[15];
}

