/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tstringstream123403 tstringstream123403;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tstream123033 tstream123033;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell38448 tcell38448;
typedef struct tcellseq38464 tcellseq38464;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38460 tcellset38460;
typedef struct tpagedesc38456 tpagedesc38456;
typedef struct tmemregion21810 tmemregion21810;
typedef struct tsmallchunk21038 tsmallchunk21038;
typedef struct tllchunk21804 tllchunk21804;
typedef struct tbigchunk21040 tbigchunk21040;
typedef struct tintset21015 tintset21015;
typedef struct ttrunk21011 ttrunk21011;
typedef struct tavlnode21808 tavlnode21808;
typedef struct tgcstat40414 tgcstat40414;
typedef struct tbasechunk21036 tbasechunk21036;
typedef struct tfreecell21028 tfreecell21028;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimObject {
TNimType* m_type;
};
typedef N_NIMCALL_PTR(void, TY123034) (tstream123033* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY123038) (tstream123033* s);
typedef N_NIMCALL_PTR(void, TY123042) (tstream123033* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY123047) (tstream123033* s);
typedef N_NIMCALL_PTR(NI, TY123051) (tstream123033* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY123057) (tstream123033* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY123063) (tstream123033* s);
struct tstream123033 {
  TNimObject Sup;
TY123034 Closeimpl;
TY123038 Atendimpl;
TY123042 Setpositionimpl;
TY123047 Getpositionimpl;
TY123051 Readdataimpl;
TY123057 Writedataimpl;
TY123063 Flushimpl;
};
struct tstringstream123403 {
  tstream123033 Sup;
NimStringDesc* Data;
NI Pos;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38448 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38464 {
NI Len;
NI Cap;
tcell38448** D;
};
struct tcellset38460 {
NI Counter;
NI Max;
tpagedesc38456* Head;
tpagedesc38456** Data;
};
typedef tsmallchunk21038* TY21822[512];
typedef ttrunk21011* ttrunkbuckets21013[256];
struct tintset21015 {
ttrunkbuckets21013 Data;
};
struct tmemregion21810 {
NI Minlargeobj;
NI Maxlargeobj;
TY21822 Freesmallchunks;
tllchunk21804* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21040* Freechunkslist;
tintset21015 Chunkstarts;
tavlnode21808* Root;
tavlnode21808* Deleted;
tavlnode21808* Last;
tavlnode21808* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38464 Zct;
tcellseq38464 Decstack;
tcellset38460 Cycleroots;
tcellseq38464 Tempstack;
NI Recgclock;
tmemregion21810 Region;
tgcstat40414 Stat;
};
typedef NI TY21018[8];
struct tpagedesc38456 {
tpagedesc38456* Next;
NI Key;
TY21018 Bits;
};
struct tbasechunk21036 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21038 {
  tbasechunk21036 Sup;
tsmallchunk21038* Next;
tsmallchunk21038* Prev;
tfreecell21028* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk21804 {
NI Size;
NI Acc;
tllchunk21804* Next;
};
struct tbigchunk21040 {
  tbasechunk21036 Sup;
tbigchunk21040* Next;
tbigchunk21040* Prev;
NI Align;
NF Data;
};
struct ttrunk21011 {
ttrunk21011* Next;
NI Key;
TY21018 Bits;
};
typedef tavlnode21808* TY21814[2];
struct tavlnode21808 {
TY21814 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21028 {
tfreecell21028* Next;
NI Zerofield;
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP121)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38448*, usrtocell_41839)(void* usr);
static N_INLINE(void, rtladdzct_43402)(tcell38448* c);
N_NOINLINE(void, addzct_41815)(tcellseq38464* s, tcell38448* c);
N_NIMCALL(void, ssclose_123486)(tstream123033* s_123488);
N_NIMCALL(NIM_BOOL, ssatend_123407)(tstream123033* s_123409);
N_NIMCALL(void, sssetposition_123414)(tstream123033* s_123416, NI pos);
N_NIMCALL(NI, clamp_123420)(NI x, NI a, NI b);
N_NIMCALL(NI, ssgetposition_123435)(tstream123033* s_123437);
N_NIMCALL(NI, ssreaddata_123442)(tstream123033* s_123444, void* buffer, NI buflen);
N_NIMCALL(void, sswritedata_123466)(tstream123033* s_123468, void* buffer, NI buflen);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(void, TMP124)(void* p, NI op);
extern TNimType NTI1009; /* TObject */
TNimType NTI123033; /* TStream */
TNimType NTI123034; /* proc (PStream) */
TNimType NTI123038; /* proc (PStream): bool */
TNimType NTI123042; /* proc (PStream, int) */
TNimType NTI123047; /* proc (PStream): int */
TNimType NTI123051; /* proc (PStream, pointer, int): int */
TNimType NTI123057; /* proc (PStream, pointer, int) */
TNimType NTI123063; /* proc (PStream) */
TNimType NTI123403; /* TStringStream */
extern TNimType NTI142; /* string */
extern TNimType NTI105; /* int */
TNimType NTI123401; /* PStringStream */
extern tgcheap40416 gch_40444;
TNimType NTI123031; /* PStream */
N_NIMCALL(void, TMP121)(void* p, NI op) {
	tstringstream123403* a;
	a = (tstringstream123403*)p;
	nimGCvisit((void*)(*a).Data, op);
}

static N_INLINE(tcell38448*, usrtocell_41839)(void* usr) {
	tcell38448* result;
	result = 0;
	result = ((tcell38448*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38448))))));
	return result;
}
static N_INLINE(void, rtladdzct_43402)(tcell38448* c) {
	addzct_41815(&gch_40444.Zct, c);}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38448* c;
	c = usrtocell_41839(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43402(c);	}	LA3: ;
}
N_NIMCALL(void, ssclose_123486)(tstream123033* s_123488) {
	tstringstream123403* s;
	NimStringDesc* LOC1;
	s = ((tstringstream123403*) (s_123488));
	LOC1 = 0;
	LOC1 = (*s).Data; (*s).Data = copyStringRC1(NIM_NIL);
	if (LOC1) nimGCunrefNoCycle(LOC1);
}
N_NIMCALL(NIM_BOOL, ssatend_123407)(tstream123033* s_123409) {
	NIM_BOOL result;
	tstringstream123403* s;
	result = 0;
	s = ((tstringstream123403*) (s_123409));
	result = ((*s).Data->Sup.len <= (*s).Pos);
	goto BeforeRet;
	BeforeRet: ;	return result;
}
N_NIMCALL(void, sssetposition_123414)(tstream123033* s_123416, NI pos) {
	tstringstream123403* s;
	s = ((tstringstream123403*) (s_123416));
	(*s).Pos = clamp_123420(pos, 0, ((*s).Data->Sup.len-1));
}
N_NIMCALL(NI, ssgetposition_123435)(tstream123033* s_123437) {
	NI result;
	tstringstream123403* s;
	result = 0;
	s = ((tstringstream123403*) (s_123437));
	result = (*s).Pos;
	goto BeforeRet;
	BeforeRet: ;	return result;
}
N_NIMCALL(NI, ssreaddata_123442)(tstream123033* s_123444, void* buffer, NI buflen) {
	NI result;
	tstringstream123403* s;
	result = 0;
	s = ((tstringstream123403*) (s_123444));
	result = ((buflen <= (NI64)((*s).Data->Sup.len - (*s).Pos)) ? buflen : (NI64)((*s).Data->Sup.len - (*s).Pos));
	{
		if (!(0 < result)) goto LA3;
		memcpy(buffer, ((void*) (&(*s).Data->data[(*s).Pos])), result);		(*s).Pos += result;
	}	LA3: ;
	return result;
}
N_NIMCALL(void, sswritedata_123466)(tstream123033* s_123468, void* buffer, NI buflen) {
	tstringstream123403* s;
	s = ((tstringstream123403*) (s_123468));
	{
		if (!(0 < buflen)) goto LA3;
		(*s).Data = setLengthStr((*s).Data, (NI64)((*s).Data->Sup.len + buflen));
		memcpy(((void*) (&(*s).Data->data[(*s).Pos])), buffer, buflen);		(*s).Pos += buflen;
	}	LA3: ;
}
N_NIMCALL(tstringstream123403*, newstringstream_123492)(NimStringDesc* s) {
	tstringstream123403* result;
	NimStringDesc* LOC1;
	result = 0;
	result = (tstringstream123403*) newObj((&NTI123401), sizeof(tstringstream123403));
	(*result).Sup.Sup.m_type = (&NTI123403);
	LOC1 = 0;
	LOC1 = (*result).Data; (*result).Data = copyStringRC1(s);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	(*result).Pos = 0;
	(*result).Sup.Closeimpl = ssclose_123486;
	(*result).Sup.Atendimpl = ssatend_123407;
	(*result).Sup.Setpositionimpl = sssetposition_123414;
	(*result).Sup.Getpositionimpl = ssgetposition_123435;
	(*result).Sup.Readdataimpl = ssreaddata_123442;
	(*result).Sup.Writedataimpl = sswritedata_123466;
	return result;
}N_NIMCALL(void, TMP124)(void* p, NI op) {
	tstream123033* a;
	a = (tstream123033*)p;
}

N_NIMCALL(NI, readdata_123135)(tstream123033* s, void* buffer, NI buflen) {
	NI result;
	result = 0;
	result = (*s).Readdataimpl(s, buffer, buflen);
	return result;
}
N_NIMCALL(void, close_123079)(tstream123033* s) {
	{
		if (!!((*s).Closeimpl == 0)) goto LA3;
		(*s).Closeimpl(s);	}	LA3: ;
}N_NOINLINE(void, purestreamsInit)(void) {
}

N_NOINLINE(void, purestreamsDatInit)(void) {
static TNimNode* TMP119[7];
static TNimNode* TMP120[2];
static TNimNode TMP34[11];
NTI123033.size = sizeof(tstream123033);
NTI123033.kind = 17;
NTI123033.base = (&NTI1009);
NTI123033.flags = 3;
TMP119[0] = &TMP34[1];
NTI123034.size = sizeof(TY123034);
NTI123034.kind = 25;
NTI123034.base = 0;
NTI123034.flags = 3;
TMP34[1].kind = 1;
TMP34[1].offset = offsetof(tstream123033, Closeimpl);
TMP34[1].typ = (&NTI123034);
TMP34[1].name = "closeImpl";
TMP119[1] = &TMP34[2];
NTI123038.size = sizeof(TY123038);
NTI123038.kind = 25;
NTI123038.base = 0;
NTI123038.flags = 3;
TMP34[2].kind = 1;
TMP34[2].offset = offsetof(tstream123033, Atendimpl);
TMP34[2].typ = (&NTI123038);
TMP34[2].name = "atEndImpl";
TMP119[2] = &TMP34[3];
NTI123042.size = sizeof(TY123042);
NTI123042.kind = 25;
NTI123042.base = 0;
NTI123042.flags = 3;
TMP34[3].kind = 1;
TMP34[3].offset = offsetof(tstream123033, Setpositionimpl);
TMP34[3].typ = (&NTI123042);
TMP34[3].name = "setPositionImpl";
TMP119[3] = &TMP34[4];
NTI123047.size = sizeof(TY123047);
NTI123047.kind = 25;
NTI123047.base = 0;
NTI123047.flags = 3;
TMP34[4].kind = 1;
TMP34[4].offset = offsetof(tstream123033, Getpositionimpl);
TMP34[4].typ = (&NTI123047);
TMP34[4].name = "getPositionImpl";
TMP119[4] = &TMP34[5];
NTI123051.size = sizeof(TY123051);
NTI123051.kind = 25;
NTI123051.base = 0;
NTI123051.flags = 3;
TMP34[5].kind = 1;
TMP34[5].offset = offsetof(tstream123033, Readdataimpl);
TMP34[5].typ = (&NTI123051);
TMP34[5].name = "readDataImpl";
TMP119[5] = &TMP34[6];
NTI123057.size = sizeof(TY123057);
NTI123057.kind = 25;
NTI123057.base = 0;
NTI123057.flags = 3;
TMP34[6].kind = 1;
TMP34[6].offset = offsetof(tstream123033, Writedataimpl);
TMP34[6].typ = (&NTI123057);
TMP34[6].name = "writeDataImpl";
TMP119[6] = &TMP34[7];
NTI123063.size = sizeof(TY123063);
NTI123063.kind = 25;
NTI123063.base = 0;
NTI123063.flags = 3;
TMP34[7].kind = 1;
TMP34[7].offset = offsetof(tstream123033, Flushimpl);
TMP34[7].typ = (&NTI123063);
TMP34[7].name = "flushImpl";
TMP34[0].len = 7; TMP34[0].kind = 2; TMP34[0].sons = &TMP119[0];
NTI123033.node = &TMP34[0];
NTI123403.size = sizeof(tstringstream123403);
NTI123403.kind = 17;
NTI123403.base = (&NTI123033);
NTI123403.flags = 2;
TMP120[0] = &TMP34[9];
TMP34[9].kind = 1;
TMP34[9].offset = offsetof(tstringstream123403, Data);
TMP34[9].typ = (&NTI142);
TMP34[9].name = "data";
TMP120[1] = &TMP34[10];
TMP34[10].kind = 1;
TMP34[10].offset = offsetof(tstringstream123403, Pos);
TMP34[10].typ = (&NTI105);
TMP34[10].name = "pos";
TMP34[8].len = 2; TMP34[8].kind = 2; TMP34[8].sons = &TMP120[0];
NTI123403.node = &TMP34[8];
NTI123401.size = sizeof(tstringstream123403*);
NTI123401.kind = 22;
NTI123401.base = (&NTI123403);
NTI123401.flags = 2;
NTI123401.marker = TMP121;
NTI123031.size = sizeof(tstream123033*);
NTI123031.kind = 22;
NTI123031.base = (&NTI123033);
NTI123031.flags = 2;
NTI123031.marker = TMP124;
}

