/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tstringtable109610 tstringtable109610;
typedef struct TNimObject TNimObject;
typedef struct tkeyvaluepairseq109608 tkeyvaluepairseq109608;
typedef struct TY86506 TY86506;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell38448 tcell38448;
typedef struct tcellseq38464 tcellseq38464;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38460 tcellset38460;
typedef struct tpagedesc38456 tpagedesc38456;
typedef struct tmemregion21810 tmemregion21810;
typedef struct tsmallchunk21038 tsmallchunk21038;
typedef struct tllchunk21804 tllchunk21804;
typedef struct tbigchunk21040 tbigchunk21040;
typedef struct tintset21015 tintset21015;
typedef struct ttrunk21011 ttrunk21011;
typedef struct tavlnode21808 tavlnode21808;
typedef struct tgcstat40414 tgcstat40414;
typedef struct tbasechunk21036 tbasechunk21036;
typedef struct tfreecell21028 tfreecell21028;
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TNimObject {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct TY86506 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tstringtable109610 {
  TNimObject Sup;
NI Counter;
tkeyvaluepairseq109608* Data;
NU8 Mode;
};
struct tcell38448 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38464 {
NI Len;
NI Cap;
tcell38448** D;
};
struct tcellset38460 {
NI Counter;
NI Max;
tpagedesc38456* Head;
tpagedesc38456** Data;
};
typedef tsmallchunk21038* TY21822[512];
typedef ttrunk21011* ttrunkbuckets21013[256];
struct tintset21015 {
ttrunkbuckets21013 Data;
};
struct tmemregion21810 {
NI Minlargeobj;
NI Maxlargeobj;
TY21822 Freesmallchunks;
tllchunk21804* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21040* Freechunkslist;
tintset21015 Chunkstarts;
tavlnode21808* Root;
tavlnode21808* Deleted;
tavlnode21808* Last;
tavlnode21808* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38464 Zct;
tcellseq38464 Decstack;
tcellset38460 Cycleroots;
tcellseq38464 Tempstack;
NI Recgclock;
tmemregion21810 Region;
tgcstat40414 Stat;
};
typedef NI TY21018[8];
struct tpagedesc38456 {
tpagedesc38456* Next;
NI Key;
TY21018 Bits;
};
struct tbasechunk21036 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21038 {
  tbasechunk21036 Sup;
tsmallchunk21038* Next;
tsmallchunk21038* Prev;
tfreecell21028* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk21804 {
NI Size;
NI Acc;
tllchunk21804* Next;
};
struct tbigchunk21040 {
  tbasechunk21036 Sup;
tbigchunk21040* Next;
tbigchunk21040* Prev;
NI Align;
NF Data;
};
struct ttrunk21011 {
ttrunk21011* Next;
NI Key;
TY21018 Bits;
};
typedef tavlnode21808* TY21814[2];
struct tavlnode21808 {
TY21814 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21028 {
tfreecell21028* Next;
NI Zerofield;
};
struct tkeyvaluepairseq109608 {
  TGenericSeq Sup;
  TY86506 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP103)(void* p, NI op);
N_NIMCALL(void, TMP107)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38448*, usrtocell_41839)(void* usr);
static N_INLINE(void, rtladdzct_43402)(tcell38448* c);
N_NOINLINE(void, addzct_41815)(tcellseq38464* s, tcell38448* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NI, rawget_109812)(tstringtable109610* t, NimStringDesc* key);
N_NIMCALL(NI, myhash_109702)(tstringtable109610* t, NimStringDesc* key);
N_NIMCALL(NI, hash_107827)(NimStringDesc* x);
N_NIMCALL(NI, hashignorecase_107925)(NimStringDesc* x);
N_NIMCALL(NI, hashignorestyle_107857)(NimStringDesc* x);
N_NIMCALL(NIM_BOOL, mycmp_109709)(tstringtable109610* t, NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, cmp_2131)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NI, nexttry_109805)(NI h, NI maxhash);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NIMCALL(NIM_BOOL, mustrehash_109717)(NI length, NI counter);
N_NIMCALL(void, enlarge_109876)(tstringtable109610* t);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, rawinsert_109864)(tstringtable109610* t, tkeyvaluepairseq109608** data, NimStringDesc* key, NimStringDesc* val);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
STRING_LITERAL(TMP150, "", 0);
extern TNimType NTI1009; /* TObject */
TNimType NTI109610; /* TStringTable */
extern TNimType NTI105; /* int */
extern TNimType NTI86506; /* tuple[nonDST: string, DST: string] */
TNimType NTI109608; /* TKeyValuePairSeq */
TNimType NTI109604; /* TStringTableMode */
TNimType NTI109612; /* PStringTable */
extern tgcheap40416 gch_40444;
N_NIMCALL(void, TMP103)(void* p, NI op) {
	tkeyvaluepairseq109608* a;
	NI LOC1;
	a = (tkeyvaluepairseq109608*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0, op);
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}
N_NIMCALL(void, TMP107)(void* p, NI op) {
	tstringtable109610* a;
	a = (tstringtable109610*)p;
	nimGCvisit((void*)(*a).Data, op);
}

static N_INLINE(tcell38448*, usrtocell_41839)(void* usr) {
	tcell38448* result;
	result = 0;
	result = ((tcell38448*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38448))))));
	return result;
}
static N_INLINE(void, rtladdzct_43402)(tcell38448* c) {
	addzct_41815(&gch_40444.Zct, c);}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38448* c;
	c = usrtocell_41839(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43402(c);	}	LA3: ;
}
N_NIMCALL(tstringtable109610*, nstnewStringTable)(NU8 mode) {
	tstringtable109610* result;
	result = 0;
	result = (tstringtable109610*) newObj((&NTI109612), sizeof(tstringtable109610));
	(*result).Sup.m_type = (&NTI109610);
	(*result).Mode = mode;
	(*result).Counter = 0;
	if ((*result).Data) nimGCunrefNoCycle((*result).Data);
	(*result).Data = (tkeyvaluepairseq109608*) newSeqRC1((&NTI109608), 64);
	return result;
}
N_NIMCALL(NI, myhash_109702)(tstringtable109610* t, NimStringDesc* key) {
	NI result;
	result = 0;
	switch ((*t).Mode) {
	case ((NU8) 0):
	{
		result = hash_107827(key);
	}	break;
	case ((NU8) 1):
	{
		result = hashignorecase_107925(key);
	}	break;
	case ((NU8) 2):
	{
		result = hashignorestyle_107857(key);
	}	break;
	}
	return result;
}
N_NIMCALL(NIM_BOOL, mycmp_109709)(tstringtable109610* t, NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	result = 0;
	switch ((*t).Mode) {
	case ((NU8) 0):
	{
		NI LOC2;
		LOC2 = 0;
		LOC2 = cmp_2131(a, b);
		result = (LOC2 == 0);
	}	break;
	case ((NU8) 1):
	{
		NI LOC4;
		LOC4 = 0;
		LOC4 = nsuCmpIgnoreCase(a, b);
		result = (LOC4 == 0);
	}	break;
	case ((NU8) 2):
	{
		NI LOC6;
		LOC6 = 0;
		LOC6 = nsuCmpIgnoreStyle(a, b);
		result = (LOC6 == 0);
	}	break;
	}
	return result;
}
static N_INLINE(NI, nexttry_109805)(NI h, NI maxhash) {
	NI result;
	result = 0;
	result = (NI)((NI64)((NI64)(5 * h) + 1) & maxhash);
	return result;
}
N_NIMCALL(NI, rawget_109812)(tstringtable109610* t, NimStringDesc* key) {
	NI result;
	NI h;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = myhash_109702(t, key);
	h = (NI)(LOC1 & ((*t).Data->Sup.len-1));
	while (1) {
		if (!!((*t).Data->data[h].Field0 == 0)) goto LA2;
		{
			NIM_BOOL LOC5;
			LOC5 = 0;
			LOC5 = mycmp_109709(t, (*t).Data->data[h].Field0, key);
			if (!LOC5) goto LA6;
			result = h;
			goto BeforeRet;
		}		LA6: ;
		h = nexttry_109805(h, ((*t).Data->Sup.len-1));
	} LA2: ;
	result = -1;
	BeforeRet: ;	return result;
}
N_NIMCALL(NIM_BOOL, mustrehash_109717)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ((NI64)(length * 2) < (NI64)(counter * 3));
	if (LOC1) goto LA2;
	LOC1 = ((NI64)(length - counter) < 4);
	LA2: ;
	result = LOC1;
	return result;
}
N_NIMCALL(void, rawinsert_109864)(tstringtable109610* t, tkeyvaluepairseq109608** data, NimStringDesc* key, NimStringDesc* val) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	LOC1 = 0;
	LOC1 = myhash_109702(t, key);
	h = (NI)(LOC1 & ((*data)->Sup.len-1));
	while (1) {
		if (!!((*data)->data[h].Field0 == 0)) goto LA2;
		h = nexttry_109805(h, ((*data)->Sup.len-1));
	} LA2: ;
	LOC3 = 0;
	LOC3 = (*data)->data[h].Field0; (*data)->data[h].Field0 = copyStringRC1(key);
	if (LOC3) nimGCunrefNoCycle(LOC3);
	LOC4 = 0;
	LOC4 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(val);
	if (LOC4) nimGCunrefNoCycle(LOC4);
}
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell38448* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_41839(src);
		(*c).Refcount += 8;
	}	LA3: ;
	{
		tcell38448* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_41839((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_43402(c);		}		LA11: ;
	}	LA7: ;
	(*dest) = src;
}
N_NIMCALL(void, enlarge_109876)(tstringtable109610* t) {
	tkeyvaluepairseq109608* n;
	NI i_109907;
	NI HEX3Atmp_109921;
	NI res_109923;
	tkeyvaluepairseq109608* LOC6;
	n = 0;
	n = (tkeyvaluepairseq109608*) newSeq((&NTI109608), (NI64)((*t).Data->Sup.len * 2));
	i_109907 = 0;
	HEX3Atmp_109921 = 0;
	HEX3Atmp_109921 = ((*t).Data->Sup.len-1);
	res_109923 = 0;
	while (1) {
		if (!(res_109923 <= HEX3Atmp_109921)) goto LA1;
		i_109907 = res_109923;
		{
			if (!!((*t).Data->data[i_109907].Field0 == 0)) goto LA4;
			rawinsert_109864(t, &n, (*t).Data->data[i_109907].Field0, (*t).Data->data[i_109907].Field1);		}		LA4: ;
		res_109923 += 1;
	} LA1: ;
	LOC6 = 0;
	LOC6 = (*t).Data;
	asgnRefNoCycle((void**) &(*t).Data, n);
	n = LOC6;
}
N_NIMCALL(void, nstPut)(tstringtable109610* t, NimStringDesc* key, NimStringDesc* val) {
	NI index;
	index = rawget_109812(t, key);
	{
		NimStringDesc* LOC5;
		if (!(0 <= index)) goto LA3;
		LOC5 = 0;
		LOC5 = (*t).Data->data[index].Field1; (*t).Data->data[index].Field1 = copyStringRC1(val);
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}	goto LA1;
	LA3: ;
	{
		{
			NIM_BOOL LOC9;
			LOC9 = 0;
			LOC9 = mustrehash_109717((*t).Data->Sup.len, (*t).Counter);
			if (!LOC9) goto LA10;
			enlarge_109876(t);		}		LA10: ;
		rawinsert_109864(t, &(*t).Data, key, val);		(*t).Counter += 1;
	}	LA1: ;
}
N_NIMCALL(NimStringDesc*, nstGet)(tstringtable109610* t, NimStringDesc* key) {
	NimStringDesc* result;
	NI index;
	result = 0;
	index = rawget_109812(t, key);
	{
		if (!(0 <= index)) goto LA3;
		result = copyString((*t).Data->data[index].Field1);
	}	goto LA1;
	LA3: ;
	{
		result = copyString(((NimStringDesc*) &TMP150));
	}	LA1: ;
	return result;
}N_NOINLINE(void, purestrtabsInit)(void) {
}

N_NOINLINE(void, purestrtabsDatInit)(void) {
static TNimNode* TMP101[3];
static TNimNode* TMP104[3];
NI TMP106;
static char* NIM_CONST TMP105[3] = {
"modeCaseSensitive", 
"modeCaseInsensitive", 
"modeStyleInsensitive"};
static TNimNode TMP21[8];
NTI109610.size = sizeof(tstringtable109610);
NTI109610.kind = 17;
NTI109610.base = (&NTI1009);
NTI109610.flags = 2;
TMP101[0] = &TMP21[1];
TMP21[1].kind = 1;
TMP21[1].offset = offsetof(tstringtable109610, Counter);
TMP21[1].typ = (&NTI105);
TMP21[1].name = "counter";
TMP101[1] = &TMP21[2];
NTI109608.size = sizeof(tkeyvaluepairseq109608*);
NTI109608.kind = 24;
NTI109608.base = (&NTI86506);
NTI109608.flags = 2;
NTI109608.marker = TMP103;
TMP21[2].kind = 1;
TMP21[2].offset = offsetof(tstringtable109610, Data);
TMP21[2].typ = (&NTI109608);
TMP21[2].name = "data";
TMP101[2] = &TMP21[3];
NTI109604.size = sizeof(NU8);
NTI109604.kind = 14;
NTI109604.base = 0;
NTI109604.flags = 3;
for (TMP106 = 0; TMP106 < 3; TMP106++) {
TMP21[TMP106+4].kind = 1;
TMP21[TMP106+4].offset = TMP106;
TMP21[TMP106+4].name = TMP105[TMP106];
TMP104[TMP106] = &TMP21[TMP106+4];
}
TMP21[7].len = 3; TMP21[7].kind = 2; TMP21[7].sons = &TMP104[0];
NTI109604.node = &TMP21[7];
TMP21[3].kind = 1;
TMP21[3].offset = offsetof(tstringtable109610, Mode);
TMP21[3].typ = (&NTI109604);
TMP21[3].name = "mode";
TMP21[0].len = 3; TMP21[0].kind = 2; TMP21[0].sons = &TMP101[0];
NTI109610.node = &TMP21[0];
NTI109612.size = sizeof(tstringtable109610*);
NTI109612.kind = 22;
NTI109612.base = (&NTI109610);
NTI109612.flags = 2;
NTI109612.marker = TMP107;
}

