/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct trstnode147011 trstnode147011;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct trstnodeseq147009 trstnodeseq147009;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell43711 tcell43711;
typedef struct tcellseq43727 tcellseq43727;
typedef struct tgcheap45616 tgcheap45616;
typedef struct tcellset43723 tcellset43723;
typedef struct tpagedesc43719 tpagedesc43719;
typedef struct tmemregion26010 tmemregion26010;
typedef struct tsmallchunk25240 tsmallchunk25240;
typedef struct tllchunk26004 tllchunk26004;
typedef struct tbigchunk25242 tbigchunk25242;
typedef struct tintset25217 tintset25217;
typedef struct ttrunk25213 ttrunk25213;
typedef struct tavlnode26008 tavlnode26008;
typedef struct tgcstat45614 tgcstat45614;
typedef struct tbasechunk25238 tbasechunk25238;
typedef struct tfreecell25230 tfreecell25230;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  trstnode147011  {
NU8 Kind;
NimStringDesc* Text;
NI Level;
trstnodeseq147009* Sons;
};
typedef N_NIMCALL_PTR(void, TY2689) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2689 marker;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell43711  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq43727  {
NI Len;
NI Cap;
tcell43711** D;
};
struct  tcellset43723  {
NI Counter;
NI Max;
tpagedesc43719* Head;
tpagedesc43719** Data;
};
typedef tsmallchunk25240* TY26022[512];
typedef ttrunk25213* ttrunkbuckets25215[256];
struct  tintset25217  {
ttrunkbuckets25215 Data;
};
struct  tmemregion26010  {
NI Minlargeobj;
NI Maxlargeobj;
TY26022 Freesmallchunks;
tllchunk26004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk25242* Freechunkslist;
tintset25217 Chunkstarts;
tavlnode26008* Root;
tavlnode26008* Deleted;
tavlnode26008* Last;
tavlnode26008* Freeavlnodes;
};
struct  tgcstat45614  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap45616  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq43727 Zct;
tcellseq43727 Decstack;
tcellset43723 Cycleroots;
tcellseq43727 Tempstack;
NI Recgclock;
tmemregion26010 Region;
tgcstat45614 Stat;
};
typedef NI TY25220[8];
struct  tpagedesc43719  {
tpagedesc43719* Next;
NI Key;
TY25220 Bits;
};
struct  tbasechunk25238  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk25240  {
  tbasechunk25238 Sup;
tsmallchunk25240* Next;
tsmallchunk25240* Prev;
tfreecell25230* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk26004  {
NI Size;
NI Acc;
tllchunk26004* Next;
};
struct  tbigchunk25242  {
  tbasechunk25238 Sup;
tbigchunk25242* Next;
tbigchunk25242* Prev;
NI Align;
NF Data;
};
struct  ttrunk25213  {
ttrunk25213* Next;
NI Key;
TY25220 Bits;
};
typedef tavlnode26008* TY26014[2];
struct  tavlnode26008  {
TY26014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell25230  {
tfreecell25230* Next;
NI Zerofield;
};
struct trstnodeseq147009 {
  TGenericSeq Sup;
  trstnode147011* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP132)(void* p, NI op);
N_NIMCALL(void, TMP133)(void* p, NI op);
N_NIMCALL(trstnode147011*, newrstnode_147105)(NU8 kind);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell43711*, usrtocell_47246)(void* usr);
static N_INLINE(void, rtladdzct_48804)(tcell43711* c);
N_NOINLINE(void, addzct_47217)(tcellseq43727* s, tcell43711* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, add_147183)(trstnode147011* father, trstnode147011* son);
TNimType NTI147011; /* TRstNode */
TNimType NTI147005; /* TRstNodeKind */
extern TNimType NTI157; /* string */
extern TNimType NTI112; /* int */
TNimType NTI147009; /* TRstNodeSeq */
TNimType NTI147007; /* PRstNode */
extern tgcheap45616 gch_45644;
N_NIMCALL(void, TMP132)(void* p, NI op) {
	trstnodeseq147009* a;
	NI LOC1;
	a = (trstnodeseq147009*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}
N_NIMCALL(void, TMP133)(void* p, NI op) {
	trstnode147011* a;
	a = (trstnode147011*)p;
	nimGCvisit((void*)(*a).Text, op);
	nimGCvisit((void*)(*a).Sons, op);
}

N_NIMCALL(NI, len_147084)(trstnode147011* n) {
	NI result;
	result = 0;
	result = (*n).Sons->Sup.len;
	return result;
}

static N_INLINE(tcell43711*, usrtocell_47246)(void* usr) {
	tcell43711* result;
	result = 0;
	result = ((tcell43711*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell43711))))));
	return result;
}

static N_INLINE(void, rtladdzct_48804)(tcell43711* c) {
	addzct_47217(&gch_45644.Zct, c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell43711* c;
	c = usrtocell_47246(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_48804(c);
	}
	LA3: ;
}

N_NIMCALL(trstnode147011*, newrstnode_147105)(NU8 kind) {
	trstnode147011* result;
	result = 0;
	result = (trstnode147011*) newObj((&NTI147007), sizeof(trstnode147011));
	if ((*result).Sons) nimGCunrefNoCycle((*result).Sons);
	(*result).Sons = (trstnodeseq147009*) newSeqRC1((&NTI147009), 0);
	(*result).Kind = kind;
	return result;
}

N_NIMCALL(trstnode147011*, newrstnode_147151)(NU8 kind, NimStringDesc* s) {
	trstnode147011* result;
	NimStringDesc* LOC1;
	result = 0;
	result = newrstnode_147105(kind);
	LOC1 = 0;
	LOC1 = (*result).Text; (*result).Text = copyStringRC1(s);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell43711* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_47246(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell43711* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_47246((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			rtladdzct_48804(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(void, add_147183)(trstnode147011* father, trstnode147011* son) {
	(*father).Sons = (trstnodeseq147009*) incrSeq(&((*father).Sons)->Sup, sizeof(trstnode147011*));
	asgnRefNoCycle((void**) &(*father).Sons->data[(*father).Sons->Sup.len-1], son);
}

N_NIMCALL(void, addifnotnil_147211)(trstnode147011* father, trstnode147011* son) {
	{
		if (!!((son == NIM_NIL))) goto LA3;
		add_147183(father, son);
	}
	LA3: ;
}

N_NIMCALL(trstnode147011*, lastson_147162)(trstnode147011* n) {
	trstnode147011* result;
	result = 0;
	result = (*n).Sons->data[(NI64)((*n).Sons->Sup.len - 1)];
	return result;
}
N_NOINLINE(void, HEX00_rstastInit)(void) {
}

N_NOINLINE(void, HEX00_rstastDatInit)(void) {
static TNimNode* TMP128[4];
static TNimNode* TMP129[65];
NI TMP131;
static char* NIM_CONST TMP130[65] = {
"rnInner", 
"rnHeadline", 
"rnOverline", 
"rnTransition", 
"rnParagraph", 
"rnBulletList", 
"rnBulletItem", 
"rnEnumList", 
"rnEnumItem", 
"rnDefList", 
"rnDefItem", 
"rnDefName", 
"rnDefBody", 
"rnFieldList", 
"rnField", 
"rnFieldName", 
"rnFieldBody", 
"rnOptionList", 
"rnOptionListItem", 
"rnOptionGroup", 
"rnOption", 
"rnOptionString", 
"rnOptionArgument", 
"rnDescription", 
"rnLiteralBlock", 
"rnQuotedLiteralBlock", 
"rnLineBlock", 
"rnLineBlockItem", 
"rnBlockQuote", 
"rnTable", 
"rnGridTable", 
"rnTableRow", 
"rnTableHeaderCell", 
"rnTableDataCell", 
"rnLabel", 
"rnFootnote", 
"rnCitation", 
"rnStandaloneHyperlink", 
"rnHyperlink", 
"rnRef", 
"rnDirective", 
"rnDirArg", 
"rnRaw", 
"rnTitle", 
"rnContents", 
"rnImage", 
"rnFigure", 
"rnCodeBlock", 
"rnRawHtml", 
"rnRawLatex", 
"rnContainer", 
"rnIndex", 
"rnSubstitutionDef", 
"rnGeneralRole", 
"rnSub", 
"rnSup", 
"rnIdx", 
"rnEmphasis", 
"rnStrongEmphasis", 
"rnTripleEmphasis", 
"rnInterpretedText", 
"rnInlineLiteral", 
"rnSubstitutionReferences", 
"rnSmiley", 
"rnLeaf"};
static TNimNode TMP23[71];
NTI147011.size = sizeof(trstnode147011);
NTI147011.kind = 18;
NTI147011.base = 0;
NTI147011.flags = 2;
TMP128[0] = &TMP23[1];
NTI147005.size = sizeof(NU8);
NTI147005.kind = 14;
NTI147005.base = 0;
NTI147005.flags = 3;
for (TMP131 = 0; TMP131 < 65; TMP131++) {
TMP23[TMP131+2].kind = 1;
TMP23[TMP131+2].offset = TMP131;
TMP23[TMP131+2].name = TMP130[TMP131];
TMP129[TMP131] = &TMP23[TMP131+2];
}
TMP23[67].len = 65; TMP23[67].kind = 2; TMP23[67].sons = &TMP129[0];
NTI147005.node = &TMP23[67];
TMP23[1].kind = 1;
TMP23[1].offset = offsetof(trstnode147011, Kind);
TMP23[1].typ = (&NTI147005);
TMP23[1].name = "kind";
TMP128[1] = &TMP23[68];
TMP23[68].kind = 1;
TMP23[68].offset = offsetof(trstnode147011, Text);
TMP23[68].typ = (&NTI157);
TMP23[68].name = "text";
TMP128[2] = &TMP23[69];
TMP23[69].kind = 1;
TMP23[69].offset = offsetof(trstnode147011, Level);
TMP23[69].typ = (&NTI112);
TMP23[69].name = "level";
TMP128[3] = &TMP23[70];
NTI147009.size = sizeof(trstnodeseq147009*);
NTI147009.kind = 24;
NTI147009.base = (&NTI147007);
NTI147009.flags = 2;
NTI147009.marker = TMP132;
TMP23[70].kind = 1;
TMP23[70].offset = offsetof(trstnode147011, Sons);
TMP23[70].typ = (&NTI147009);
TMP23[70].name = "sons";
TMP23[0].len = 4; TMP23[0].kind = 2; TMP23[0].sons = &TMP128[0];
NTI147011.node = &TMP23[0];
NTI147007.size = sizeof(trstnode147011*);
NTI147007.kind = 22;
NTI147007.base = (&NTI147011);
NTI147007.flags = 2;
NTI147007.marker = TMP133;
}

