/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct EOverflow EOverflow;
typedef struct earithmetic2843 earithmetic2843;
typedef struct esynch2831 esynch2831;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell43711 tcell43711;
typedef struct tcellseq43727 tcellseq43727;
typedef struct tgcheap45616 tgcheap45616;
typedef struct tcellset43723 tcellset43723;
typedef struct tpagedesc43719 tpagedesc43719;
typedef struct tmemregion26010 tmemregion26010;
typedef struct tsmallchunk25240 tsmallchunk25240;
typedef struct tllchunk26004 tllchunk26004;
typedef struct tbigchunk25242 tbigchunk25242;
typedef struct tintset25217 tintset25217;
typedef struct ttrunk25213 ttrunk25213;
typedef struct tavlnode26008 tavlnode26008;
typedef struct tgcstat45614 tgcstat45614;
typedef struct tbasechunk25238 tbasechunk25238;
typedef struct tfreecell25230 tfreecell25230;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY2689) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2689 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  esynch2831  {
  E_Base Sup;
};
struct  earithmetic2843  {
  esynch2831 Sup;
};
struct  EOverflow  {
  earithmetic2843 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell43711  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq43727  {
NI Len;
NI Cap;
tcell43711** D;
};
struct  tcellset43723  {
NI Counter;
NI Max;
tpagedesc43719* Head;
tpagedesc43719** Data;
};
typedef tsmallchunk25240* TY26022[512];
typedef ttrunk25213* ttrunkbuckets25215[256];
struct  tintset25217  {
ttrunkbuckets25215 Data;
};
struct  tmemregion26010  {
NI Minlargeobj;
NI Maxlargeobj;
TY26022 Freesmallchunks;
tllchunk26004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk25242* Freechunkslist;
tintset25217 Chunkstarts;
tavlnode26008* Root;
tavlnode26008* Deleted;
tavlnode26008* Last;
tavlnode26008* Freeavlnodes;
};
struct  tgcstat45614  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap45616  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq43727 Zct;
tcellseq43727 Decstack;
tcellset43723 Cycleroots;
tcellseq43727 Tempstack;
NI Recgclock;
tmemregion26010 Region;
tgcstat45614 Stat;
};
typedef NI TY25220[8];
struct  tpagedesc43719  {
tpagedesc43719* Next;
NI Key;
TY25220 Bits;
};
struct  tbasechunk25238  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk25240  {
  tbasechunk25238 Sup;
tsmallchunk25240* Next;
tsmallchunk25240* Prev;
tfreecell25230* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk26004  {
NI Size;
NI Acc;
tllchunk26004* Next;
};
struct  tbigchunk25242  {
  tbasechunk25238 Sup;
tbigchunk25242* Next;
tbigchunk25242* Prev;
NI Align;
NF Data;
};
struct  ttrunk25213  {
ttrunk25213* Next;
NI Key;
TY25220 Bits;
};
typedef tavlnode26008* TY26014[2];
struct  tavlnode26008  {
TY26014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell25230  {
tfreecell25230* Next;
NI Zerofield;
};
N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start);
N_NIMCALL(NI, rawparseint_86555)(NimStringDesc* s, NI64* b, NI start);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI64, mulInt64)(NI64 a, NI64 b);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI64, subInt64)(NI64 a, NI64 b);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell43711*, usrtocell_47246)(void* usr);
static N_INLINE(void, rtladdzct_48804)(tcell43711* c);
N_NOINLINE(void, addzct_47217)(tcellseq43727* s, tcell43711* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
STRING_LITERAL(TMP184, "overflow", 8);
extern TNimType NTI21001; /* ref EOverflow */
extern TNimType NTI2847; /* EOverflow */
extern tgcheap45616 gch_45644;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI64, subInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	result = (NI64)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI64)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI64)(result ^ (NI64)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, rawparseint_86555)(NimStringDesc* s, NI64* b, NI start) {
	NI result;
	NI64 sign;
	NI i;
	result = 0;
	sign = -1;
	i = start;
	{
		if (!((NU8)(s->data[i]) == (NU8)(43))) goto LA3;
		i = addInt(i, 1);
	}
	goto LA1;
	LA3: ;
	{
		if (!((NU8)(s->data[i]) == (NU8)(45))) goto LA6;
		i = addInt(i, 1);
		sign = 1;
	}
	goto LA1;
	LA6: ;
	LA1: ;
	{
		NI64 TMP182;
		NI TMP183;
		if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA10;
		(*b) = 0;
		while (1) {
			NI64 TMP179;
			NI TMP180;
			NI64 TMP181;
			if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA12;
			TMP179 = mulInt64((*b), 10);
			TMP180 = subInt(((NI) (((NU8)(s->data[i])))), 48);
			TMP181 = subInt64((NI64)(TMP179), ((NI64) ((NI64)(TMP180))));
			(*b) = (NI64)(TMP181);
			i = addInt(i, 1);
			while (1) {
				if (!((NU8)(s->data[i]) == (NU8)(95))) goto LA13;
				i = addInt(i, 1);
			} LA13: ;
		} LA12: ;
		TMP182 = mulInt64((*b), sign);
		(*b) = (NI64)(TMP182);
		TMP183 = subInt(i, start);
		result = (NI64)(TMP183);
	}
	LA10: ;
	return result;
}

N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start) {
	NI result;
	NI64 res;
	result = 0;
	res = 0;
	result = rawparseint_86555(s, &res, start);
	(*number) = res;
	return result;
}

static N_INLINE(tcell43711*, usrtocell_47246)(void* usr) {
	tcell43711* result;
	result = 0;
	result = ((tcell43711*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell43711))))));
	return result;
}

static N_INLINE(void, rtladdzct_48804)(tcell43711* c) {
	addzct_47217(&gch_45644.Zct, c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell43711* c;
	c = usrtocell_47246(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_48804(c);
	}
	LA3: ;
}

N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start) {
	NI result;
	NI64 res;
	result = 0;
	res = 0;
	result = npuParseBiggestInt(s, &res, start);
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC5;
		EOverflow* e_86708;
		NimStringDesc* LOC9;
		LOC3 = 0;
		LOC3 = NIM_FALSE;
		if (!(LOC3)) goto LA4;
		LOC5 = 0;
		LOC5 = (res < (IL64(-9223372036854775807) - IL64(1)));
		if (LOC5) goto LA6;
		LOC5 = (IL64(9223372036854775807) < res);
		LA6: ;
		LOC3 = LOC5;
		LA4: ;
		if (!LOC3) goto LA7;
		e_86708 = 0;
		e_86708 = (EOverflow*) newObj((&NTI21001), sizeof(EOverflow));
		(*e_86708).Sup.Sup.Sup.Sup.m_type = (&NTI2847);
		LOC9 = 0;
		LOC9 = (*e_86708).Sup.Sup.Sup.message; (*e_86708).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP184));
		if (LOC9) nimGCunrefNoCycle(LOC9);
		raiseException((E_Base*)e_86708, "EOverflow");
	}
	goto LA1;
	LA7: ;
	{
		(*number) = ((NI) (res));
	}
	LA1: ;
	return result;
}
N_NOINLINE(void, stdlib_parseutilsInit)(void) {
}

N_NOINLINE(void, stdlib_parseutilsDatInit)(void) {
}

